export const sportOptions = [
  { id: "running", label: "Running", route: true, workout: false, metric: "pace" },
  { id: "trail_running", label: "Trail Running", route: true, workout: false, metric: "pace" },
  { id: "road_cycling", label: "Road Cycling", route: true, workout: false, metric: "speed" },
  { id: "gravel_cycling", label: "Gravel Cycling", route: true, workout: false, metric: "speed" },
  { id: "mountain_biking", label: "Mountain Biking", route: true, workout: false, metric: "speed" },
  { id: "walking", label: "Walking", route: true, workout: false, metric: "speed" },
  { id: "kayaking", label: "Kayaking", route: true, workout: false, metric: "speed" },
  { id: "strength_training", label: "Strength Training", route: false, workout: true, metric: "intensity" },
  { id: "crossfit", label: "CrossFit", route: false, workout: true, metric: "intensity" },
  { id: "hyrox", label: "HYROX", route: false, workout: true, metric: "intensity" },
  { id: "bootcamp", label: "Bootcamp", route: false, workout: true, metric: "intensity" },
  { id: "swimming", label: "Swimming", route: false, workout: false, metric: "intensity" },
  { id: "padel", label: "Padel", route: false, workout: false, metric: "intensity" },
];
