import { getSportLabel } from "../trainingHelpers";

export function pickPlaceNameFromLabel(value) {
  const raw = String(value || "").trim();
  if (!raw) return "";

  const parts = raw
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean)
    .filter((part) => !/^(netherlands|nederland)$/i.test(part));

  const postalCodeIndex = parts.findIndex((part) => /\b\d{4}\s?[A-Z]{2}\b/i.test(part));
  if (postalCodeIndex >= 0 && parts[postalCodeIndex + 1]) return parts[postalCodeIndex + 1];

  const likelyPlace = parts.find(
    (part) => !/^(street|road|route|unnamed|current location|startlocatie)$/i.test(part) && !/\d/.test(part)
  );
  return likelyPlace || parts[0] || "";
}

export function cleanRouteLocationName(value) {
  const place = pickPlaceNameFromLabel(value);
  if (!place || /^(locatie bepalen|startlocatie|current location)$/i.test(place)) return "";
  return place;
}

export function formatRouteDistanceLabel(value) {
  const distance = Number(value);
  if (!Number.isFinite(distance) || distance <= 0) return "0.0 km";
  return `${distance.toFixed(1)} km`;
}

export function buildAutomaticRouteTitle({ startLocation, distanceKm, sportId }) {
  const location = cleanRouteLocationName(startLocation);
  const distance = Number(distanceKm);

  if (!location || !Number.isFinite(distance) || distance <= 0) return "";
  return `${location} - ${formatRouteDistanceLabel(distance)} - ${getSportLabel(sportId || "running")}`;
}

export function isPlaceholderRouteTitle(value) {
  const raw = String(value || "").trim();
  return !raw || /^locatie bepalen\s*-/i.test(raw) || /^route\s*-\s*0(?:\.0)?\s*km\s*-/i.test(raw);
}

export function isAutoGeneratedRouteTitle(value, sportId) {
  const raw = String(value || "").trim();
  if (!raw) return true;
  if (isPlaceholderRouteTitle(raw)) return true;

  const sportLabel = getSportLabel(sportId || "running").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const autoPattern = new RegExp(`^.+\\s-\\s\\d+(?:[.,]\\d+)?\\s?km\\s-\\s${sportLabel}$`, "i");
  return autoPattern.test(raw);
}

export function cleanHumanLocationLabel(value) {
  return String(value || "")
    .trim()
    .replace(/,?\s*(Nederland|Netherlands)\s*$/i, "")
    .replace(/\s{2,}/g, " ")
    .trim();
}

export function pickHumanLocationLabel(data) {
  return cleanHumanLocationLabel(
    data?.label ||
    data?.name ||
    data?.display_name ||
    data?.place ||
    data?.city ||
    data?.town ||
    data?.village ||
    data?.municipality ||
    data?.locality ||
    data?.county ||
    ""
  );
}
