// lib/routes/sportRouteProfiles.js
// Explicit sport routing profiles. The route API uses these profiles to score
// candidate segments. Sport choice should be enough; do not add duplicate
// "prefer paved/trail" buttons in the UI.

export const SPORT_ROUTE_PROFILES = {
  running: {
    label: "Running",
    providerProfiles: ["cycling-regular", "cycling-road", "foot-walking"],
    preferences: ["recommended", "fastest"],
    maxDetourFactor: 1.6,
    earlyAcceptScore: 94,
    alternativeWeightFactor: 1.8,
    alternativeShareFactor: 0.45,
    detourPenaltyScale: 22,
    elevationBonusPerKm: 0,
    suitableSurfaces: ["asphalt", "paved", "concrete", "paving_stones", "compacted", "fine_gravel"],
    unsuitableSurfaces: ["mud", "sand", "grass", "dirt", "ground", "unpaved"],
    suitableWaytypes: ["cycleway", "street", "road", "pedestrian", "footway"],
    unsuitableWaytypes: ["steps", "ferry", "track"],
    surfaceWeights: {
      asphalt: 42,
      paved: 38,
      concrete: 34,
      paving_stones: 26,
      compacted: 18,
      fine_gravel: 10,
      gravel: -10,
      unpaved: -24,
      dirt: -34,
      ground: -34,
      earth: -34,
      grass: -34,
      sand: -45,
      mud: -50,
    },
    waytypeWeights: {
      cycleway: 22,
      street: 18,
      road: 14,
      pedestrian: 12,
      footway: 10,
      path: -10,
      track: -22,
      state_road: -12,
      steps: -50,
    },
  },

  trail_running: {
    label: "Trail Running",
    providerProfiles: ["foot-hiking", "foot-walking"],
    preferences: ["recommended", "shortest"],
    maxDetourFactor: 1.95,
    earlyAcceptScore: 93,
    alternativeWeightFactor: 1.9,
    alternativeShareFactor: 0.45,
    detourPenaltyScale: 14,
    elevationBonusPerKm: 0.75,
    maxElevationBonus: 20,
    suitableSurfaces: ["ground", "dirt", "earth", "grass", "gravel", "fine_gravel", "compacted", "woodchips", "unpaved"],
    unsuitableSurfaces: ["asphalt", "paved", "concrete", "paving_stones", "sand", "mud"],
    suitableWaytypes: ["path", "track", "footway"],
    unsuitableWaytypes: ["state_road", "road", "street", "cycleway"],
    surfaceWeights: {
      dirt: 42,
      ground: 42,
      earth: 42,
      unpaved: 36,
      woodchips: 34,
      grass: 24,
      gravel: 22,
      fine_gravel: 18,
      compacted: 10,
      asphalt: -42,
      paved: -38,
      concrete: -36,
      paving_stones: -24,
      sand: -18,
      mud: -20,
    },
    waytypeWeights: {
      path: 34,
      track: 30,
      footway: 12,
      cycleway: -24,
      street: -26,
      road: -32,
      state_road: -40,
      steps: -20,
    },
  },

  road_cycling: {
    label: "Road Cycling",
    providerProfiles: ["cycling-road", "cycling-regular"],
    preferences: ["recommended", "fastest"],
    maxDetourFactor: 1.18,
    earlyAcceptScore: 90,
    alternativeWeightFactor: 1.35,
    alternativeShareFactor: 0.6,
    detourPenaltyScale: 42,
    suitableSurfaces: ["asphalt", "paved", "concrete"],
    unsuitableSurfaces: ["ground", "dirt", "mud", "sand", "grass", "unpaved"],
    suitableWaytypes: ["cycleway", "street", "road"],
    unsuitableWaytypes: ["path", "steps"],
    surfaceWeights: {
      asphalt: 40,
      paved: 34,
      concrete: 28,
      compacted: -8,
      fine_gravel: -14,
      gravel: -25,
      unpaved: -35,
      dirt: -45,
      ground: -45,
      sand: -50,
      mud: -55,
    },
    waytypeWeights: {
      cycleway: 20,
      street: 16,
      road: 14,
      path: -30,
      track: -20,
      steps: -60,
    },
  },

  gravel_cycling: {
    label: "Gravel Cycling",
    providerProfiles: ["cycling-mountain", "cycling-regular"],
    preferences: ["recommended", "shortest"],
    maxDetourFactor: 1.55,
    earlyAcceptScore: 90,
    alternativeWeightFactor: 1.8,
    alternativeShareFactor: 0.5,
    detourPenaltyScale: 18,
    suitableSurfaces: ["gravel", "fine_gravel", "compacted", "ground", "dirt", "earth", "unpaved"],
    unsuitableSurfaces: ["sand", "mud", "grass"],
    suitableWaytypes: ["track", "path", "cycleway"],
    unsuitableWaytypes: ["steps", "state_road"],
    surfaceWeights: {
      fine_gravel: 38,
      gravel: 36,
      compacted: 34,
      unpaved: 26,
      ground: 20,
      dirt: 20,
      earth: 20,
      asphalt: 4,
      paved: 4,
      sand: -35,
      mud: -40,
      grass: -18,
    },
    waytypeWeights: {
      track: 28,
      path: 18,
      cycleway: 8,
      street: -6,
      road: -10,
      state_road: -30,
      steps: -50,
    },
  },

  mountain_biking: {
    label: "Mountain Biking",
    providerProfiles: ["cycling-mountain", "foot-hiking", "cycling-regular"],
    preferences: ["recommended", "shortest"],
    maxDetourFactor: 1.75,
    earlyAcceptScore: 91,
    alternativeWeightFactor: 1.9,
    alternativeShareFactor: 0.45,
    detourPenaltyScale: 14,
    elevationBonusPerKm: 0.35,
    maxElevationBonus: 12,
    suitableSurfaces: ["ground", "dirt", "earth", "grass", "gravel", "fine_gravel", "woodchips", "compacted", "unpaved"],
    unsuitableSurfaces: ["sand", "mud"],
    suitableWaytypes: ["path", "track"],
    unsuitableWaytypes: ["state_road", "steps"],
    surfaceWeights: {
      dirt: 36,
      ground: 36,
      earth: 36,
      unpaved: 34,
      woodchips: 32,
      gravel: 26,
      fine_gravel: 22,
      compacted: 18,
      grass: 10,
      asphalt: -8,
      paved: -8,
      sand: -22,
      mud: -18,
    },
    waytypeWeights: {
      path: 34,
      track: 32,
      footway: 6,
      cycleway: -8,
      street: -16,
      road: -18,
      state_road: -35,
      steps: -45,
    },
  },

  walking: {
    label: "Walking",
    providerProfiles: ["foot-walking", "foot-hiking"],
    preferences: ["recommended", "shortest"],
    maxDetourFactor: 1.4,
    earlyAcceptScore: 90,
    alternativeWeightFactor: 1.5,
    alternativeShareFactor: 0.55,
    detourPenaltyScale: 24,
    suitableSurfaces: ["asphalt", "paved", "concrete", "paving_stones", "compacted", "fine_gravel", "ground"],
    unsuitableSurfaces: ["mud", "sand"],
    suitableWaytypes: ["footway", "path", "pedestrian", "track"],
    unsuitableWaytypes: ["state_road"],
    surfaceWeights: {
      asphalt: 18,
      paved: 18,
      concrete: 14,
      paving_stones: 12,
      compacted: 16,
      fine_gravel: 12,
      ground: 10,
      dirt: 8,
      sand: -20,
      mud: -25,
    },
    waytypeWeights: {
      footway: 18,
      path: 16,
      pedestrian: 14,
      track: 10,
      street: 4,
      road: -8,
      state_road: -30,
    },
  },
};

export function normalizeSportId(value) {
  const key = String(value || "running").toLowerCase();
  if (key === "trailrunning") return "trail_running";
  if (key === "roadcycling") return "road_cycling";
  if (key === "gravel") return "gravel_cycling";
  if (key === "mtb") return "mountain_biking";
  return SPORT_ROUTE_PROFILES[key] ? key : "running";
}

export function getSportRouteProfile(value) {
  return SPORT_ROUTE_PROFILES[normalizeSportId(value)] || SPORT_ROUTE_PROFILES.running;
}

export function getProviderProfiles(value) {
  return getSportRouteProfile(value).providerProfiles;
}

export function getRoutingPreferences(value) {
  return getSportRouteProfile(value).preferences;
}

export const WAYTYPE_LABELS = {
  0: "unknown",
  1: "state_road",
  2: "road",
  3: "street",
  4: "path",
  5: "track",
  6: "cycleway",
  7: "footway",
  8: "steps",
  9: "ferry",
  10: "construction",
};

export const SURFACE_LABELS = {
  0: "unknown",
  1: "paved",
  2: "unpaved",
  3: "asphalt",
  4: "concrete",
  5: "cobblestone",
  6: "metal",
  7: "wood",
  8: "compacted",
  9: "fine_gravel",
  10: "gravel",
  11: "dirt",
  12: "ground",
  13: "ice",
  14: "paving_stones",
  15: "sand",
  16: "woodchips",
  17: "grass",
  18: "grass_paver",
};
