// components/routes/FullscreenRouteDrawPage.js
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import RouteDrawMap from "./RouteDrawMap";
import { supabase } from "../../lib/supabase";
import { getSportLabel } from "../../lib/trainingHelpers";
import { calculateRouteMetrics, normalizeRoutePoints, simplifyRoutePoints } from "../../lib/routeMetrics";

function defaultTitle(sportId) {
  return `${getSportLabel(sportId || "running")} Route`;
}

function cleanHumanLocationLabel(value) {
  return String(value || "")
    .trim()
    .replace(/,?\s*(Nederland|Netherlands)\s*$/i, "")
    .replace(/\s{2,}/g, " ")
    .trim();
}

function pickPlaceNameFromLabel(value) {
  const raw = cleanHumanLocationLabel(value);
  if (!raw) return "";

  const parts = raw
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean)
    .filter((part) => !/^(netherlands|nederland)$/i.test(part));

  const postalCodeIndex = parts.findIndex((part) => /\b\d{4}\s?[A-Z]{2}\b/i.test(part));
  if (postalCodeIndex >= 0 && parts[postalCodeIndex + 1]) return parts[postalCodeIndex + 1];

  return parts.find((part) => !/^(street|road|route|unnamed|current location|startlocatie|locatie bepalen)$/i.test(part) && !/\d/.test(part)) || parts[0] || "";
}

function cleanRouteLocationName(value) {
  const place = pickPlaceNameFromLabel(value);
  if (!place || /^(locatie bepalen|startlocatie|current location)$/i.test(place)) return "";
  return place;
}

function formatRouteDistanceLabel(value) {
  const distance = Number(value);
  if (!Number.isFinite(distance) || distance <= 0) return "0.0 km";
  return `${distance.toFixed(1)} km`;
}

function buildAutomaticRouteTitle({ startLocation, distanceKm, sportId }) {
  const location = cleanRouteLocationName(startLocation);
  const distance = Number(distanceKm);
  if (!location || !Number.isFinite(distance) || distance <= 0) return "";
  return `${location} - ${formatRouteDistanceLabel(distance)} - ${getSportLabel(sportId || "running")}`;
}

function isPlaceholderRouteTitle(value) {
  const raw = String(value || "").trim();
  return !raw || /^locatie bepalen\s*-/i.test(raw) || /^route\s*-\s*0(?:\.0)?\s*km\s*-/i.test(raw);
}

function isAutoGeneratedRouteTitle(value, sportId) {
  const raw = String(value || "").trim();
  if (!raw || isPlaceholderRouteTitle(raw)) return true;
  const sportLabel = getSportLabel(sportId || "running").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`^.+\\s-\\s\\d+(?:[.,]\\d+)?\\s?km\\s-\\s${sportLabel}$`, "i").test(raw);
}

function compactRoutePoints(points, maxPoints = 900) {
  const normalized = normalizeRoutePoints(points);
  const simplified = simplifyRoutePoints(normalized, normalized.length > 350 ? 6 : 2.5);

  if (simplified.length <= maxPoints) return simplified;

  const step = Math.ceil(simplified.length / maxPoints);
  const compacted = simplified.filter((_, index) => index % step === 0);
  const last = simplified[simplified.length - 1];

  if (last && compacted[compacted.length - 1] !== last) compacted.push(last);
  return compacted;
}

function compactControlPoints(points, maxPoints = 14) {
  const normalized = normalizeRoutePoints(points);
  if (normalized.length <= maxPoints) return normalized;

  const result = [];
  const lastIndex = normalized.length - 1;

  for (let index = 0; index < maxPoints; index += 1) {
    const sourceIndex = Math.round((index / (maxPoints - 1)) * lastIndex);
    const point = normalized[sourceIndex];
    const previous = result[result.length - 1];
    if (point && (!previous || previous.lat !== point.lat || previous.lon !== point.lon)) result.push(point);
  }

  const first = normalized[0];
  const last = normalized[lastIndex];
  if (first && (result[0]?.lat !== first.lat || result[0]?.lon !== first.lon)) result.unshift(first);
  if (last && (result[result.length - 1]?.lat !== last.lat || result[result.length - 1]?.lon !== last.lon)) result.push(last);
  return result;
}

function makeRoutePointPayload(points, source = "draw-fullscreen") {
  const normalized = normalizeRoutePoints(points);
  const metrics = calculateRouteMetrics(normalized);

  return {
    source,
    points: normalized,
    point_count: normalized.length,
    distance_km: metrics.distance_km || null,
    elevation_gain_m: metrics.elevation_gain_m || 0,
    elevation_loss_m: metrics.elevation_loss_m || 0,
    max_elevation_m: metrics.max_elevation_m || null,
    drawn_at: new Date().toISOString(),
  };
}

function buildSafeRoutePayload(payload, fallbackPoints, controlPoints) {
  const payloadPoints = normalizeRoutePoints(payload?.points?.length ? payload.points : payload);
  const fallback = normalizeRoutePoints(fallbackPoints);
  const points = compactRoutePoints(payloadPoints.length ? payloadPoints : fallback);
  const controls = compactControlPoints(controlPoints?.length ? controlPoints : fallback, 80);
  const metrics = calculateRouteMetrics(points);

  return {
    ...(payload && typeof payload === "object" && !Array.isArray(payload) ? payload : {}),
    source: payload?.source || "draw-fullscreen",
    points,
    waypoints: controls,
    control_points: controls,
    geometry_points: points,
    point_count: points.length,
    distance_km: metrics.distance_km || payload?.distance_km || null,
    elevation_gain_m: metrics.elevation_gain_m || payload?.elevation_gain_m || 0,
    edited_at: new Date().toISOString(),
  };
}

function safeReadEditDraft() {
  if (typeof window === "undefined") return null;

  try {
    const raw = window.sessionStorage.getItem("endurance_route_edit_draft");
    return raw ? JSON.parse(raw) : null;
  } catch (error) {
    console.warn("Could not read route edit draft", error);
    return null;
  }
}

function routePointsToGpx(points, name = "Endurance Route") {
  const normalized = normalizeRoutePoints(points);
  const escape = (value = "") => String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&apos;");
  const trackPoints = normalized
    .map((point) => {
      const ele = Number.isFinite(Number(point.ele)) ? `\n        <ele>${Number(point.ele).toFixed(1)}</ele>` : "";
      return `      <trkpt lat="${Number(point.lat).toFixed(6)}" lon="${Number(point.lon).toFixed(6)}">${ele}\n      </trkpt>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="Endurance" xmlns="http://www.topografix.com/GPX/1/1">\n  <metadata>\n    <name>${escape(name)}</name>\n    <time>${new Date().toISOString()}</time>\n  </metadata>\n  <trk>\n    <name>${escape(name)}</name>\n    <trkseg>\n${trackPoints}\n    </trkseg>\n  </trk>\n</gpx>`;
}

async function resolveHumanLocationLabelFromCoordinates(point) {
  const lat = Number(point?.lat);
  const lon = Number(point?.lon);
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) return "";

  try {
    const response = await fetch(`/api/geocode/reverse?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}`);
    if (!response.ok) return "";
    const data = await response.json();
    return cleanHumanLocationLabel(data?.label || data?.name || data?.display_name || data?.place || data?.city || data?.town || data?.village || data?.municipality || data?.locality || data?.county || "");
  } catch (error) {
    console.warn("Could not resolve route location", error);
    return "";
  }
}

export default function FullscreenRouteDrawPage() {
  const router = useRouter();
  const loadedDraftRef = useRef(false);
  const currentLocationRequestedRef = useRef(false);
  const routeStartLookupRef = useRef("");

  const [profile, setProfile] = useState(null);
  const [sportId, setSportId] = useState("");
  const [title, setTitle] = useState("Draw Route");
  const [pointsPayload, setPointsPayload] = useState(null);
  const [routedPayload, setRoutedPayload] = useState(null);
  const [message, setMessage] = useState("");
  const [checking, setChecking] = useState(true);
  const [routeStartLocation, setRouteStartLocation] = useState("Locatie bepalen");
  const [titleEditedManually, setTitleEditedManually] = useState(false);
  const [currentLocation, setCurrentLocation] = useState(null);
  const [targetLocation, setTargetLocation] = useState(null);
  const [editRouteId, setEditRouteId] = useState("");
  const [editReturnTo, setEditReturnTo] = useState("");
  const [isImportedEditRoute, setIsImportedEditRoute] = useState(false);
  const [gpxGeometryLocked, setGpxGeometryLocked] = useState(false);

  const points = useMemo(() => normalizeRoutePoints(pointsPayload), [pointsPayload]);
  const routedPoints = useMemo(() => normalizeRoutePoints(routedPayload), [routedPayload]);
  const activeRoutePayload = routedPayload || pointsPayload;
  const metrics = useMemo(() => calculateRouteMetrics(activeRoutePayload), [activeRoutePayload]);
  const canContinue = points.length >= 2 || routedPoints.length >= 2;
  const mapPerformanceMode = isImportedEditRoute && gpxGeometryLocked ? "gpx-edit" : "normal";

  useEffect(() => {
    async function bootstrap() {
      setChecking(true);

      try {
        const params = new URLSearchParams(window.location.search);
        const editDraft = safeReadEditDraft();
        const draftRouteId = editDraft?.edit_route_id || params.get("routeId") || "";
        const draftReturnTo = editDraft?.return_to || params.get("returnTo") || (draftRouteId ? `/routes/${draftRouteId}` : "");
        const initialSport = params.get("sport_id") || editDraft?.sport_id;

        if (!initialSport) {
          router.replace("/routes/new");
          return;
        }

        setSportId(initialSport);
        setEditRouteId(draftRouteId);
        setEditReturnTo(draftReturnTo);
        setTitle(editDraft?.title || defaultTitle(initialSport));
        setTitleEditedManually(!(editDraft?.title_is_auto !== false || isAutoGeneratedRouteTitle(editDraft?.title, initialSport)));

        if (editDraft?.route_points?.points?.length) {
          loadedDraftRef.current = true;
          const geometry = normalizeRoutePoints(editDraft.route_points.points);
          const savedControls = normalizeRoutePoints(editDraft.route_points.waypoints || editDraft.route_points.control_points);
          const source = String(editDraft.route_points.source || "").toLowerCase();
          const isImportedGpx = Boolean(draftRouteId) && (source.includes("gpx") || Boolean(editDraft?.gpx_file_url) || (geometry.length > 180 && savedControls.length < 3));
          const controls = isImportedGpx ? compactControlPoints(geometry, 2) : savedControls.length >= 2 ? compactControlPoints(savedControls) : compactControlPoints(geometry);

          setIsImportedEditRoute(isImportedGpx);
          setGpxGeometryLocked(isImportedGpx);
          setPointsPayload(makeRoutePointPayload(controls, isImportedGpx ? "gpx-edit-control-points" : "draw-edit-control-points"));
          setRoutedPayload({
            ...editDraft.route_points,
            points: geometry,
            waypoints: controls,
            control_points: controls,
            point_count: geometry.length,
          });
          window.sessionStorage.removeItem("endurance_route_edit_draft");
        }

        const { data } = await supabase.auth.getUser();
        const user = data?.user;

        if (!user?.id) {
          router.replace("/login");
          return;
        }

        const { data: profileRow, error } = await supabase
          .from("profiles")
          .select("id,name,email,avatar_url,role,onboarding_completed,blocked")
          .eq("id", user.id)
          .maybeSingle();

        if (error) throw error;
        if (!profileRow?.onboarding_completed) {
          router.replace("/onboarding");
          return;
        }
        if (profileRow?.blocked) {
          setMessage("Your account is blocked. Contact an administrator.");
          return;
        }

        setProfile(profileRow);
      } catch (error) {
        console.error("Draw route bootstrap error", error);
        setMessage(error?.message || "Could not open draw editor.");
      } finally {
        setChecking(false);
      }
    }

    bootstrap();
  }, [router]);

  useEffect(() => {
    const firstPoint = routedPoints[0] || points[0];

    if (!firstPoint) {
      routeStartLookupRef.current = "";
      if (!titleEditedManually) setRouteStartLocation("Locatie bepalen");
      return;
    }

    const key = `${Number(firstPoint.lat).toFixed(5)},${Number(firstPoint.lon).toFixed(5)}`;
    if (routeStartLookupRef.current === key) return;
    routeStartLookupRef.current = key;

    let cancelled = false;
    resolveHumanLocationLabelFromCoordinates(firstPoint).then((label) => {
      if (!cancelled && label) setRouteStartLocation(label);
    });

    return () => {
      cancelled = true;
    };
  }, [points, routedPoints, titleEditedManually]);

  useEffect(() => {
    if (titleEditedManually) return;

    const generatedTitle = buildAutomaticRouteTitle({
      startLocation: routeStartLocation,
      distanceKm: metrics.distance_km || routedPayload?.distance_km || pointsPayload?.distance_km || 0,
      sportId,
    });

    if (generatedTitle) setTitle(generatedTitle);
  }, [titleEditedManually, routeStartLocation, metrics.distance_km, routedPayload?.distance_km, pointsPayload?.distance_km, sportId]);

  useEffect(() => {
    if (checking || currentLocationRequestedRef.current || loadedDraftRef.current) return;
    currentLocationRequestedRef.current = true;
    requestCurrentLocation({ focus: true, quiet: true });
  }, [checking]);

  function requestCurrentLocation({ focus = true, quiet = false } = {}) {
    if (!navigator.geolocation) {
      if (!quiet) setMessage("Geolocation is not available on this device.");
      return;
    }

    navigator.geolocation.getCurrentPosition(
      (position) => {
        const location = {
          lat: Number(position.coords.latitude.toFixed(6)),
          lon: Number(position.coords.longitude.toFixed(6)),
          accuracy: Math.round(position.coords.accuracy || 35),
          label: "Current location",
        };

        setCurrentLocation(location);
        if (focus && !points.length && !routedPoints.length) {
          setTargetLocation({ ...location, selectedAt: Date.now(), zoom: 15 });
        }
      },
      () => {
        if (!quiet) setMessage("Could not access current location. You can still draw manually.");
      },
      { enableHighAccuracy: true, timeout: 9000, maximumAge: 60000 }
    );
  }

  function handlePointsChange(nextPoints) {
    if (isImportedEditRoute && gpxGeometryLocked) {
      setMessage("GPX route is shown in lightweight mode. Tap Convert to editable before changing the geometry.");
      return;
    }

    const controls = compactControlPoints(nextPoints);
    loadedDraftRef.current = false;
    setPointsPayload(makeRoutePointPayload(controls));
    setRoutedPayload(null);
    setMessage("");
  }

  function convertGpxToEditableRoute() {
    const geometry = normalizeRoutePoints(routedPayload?.points?.length ? routedPayload.points : activeRoutePayload);
    const controls = compactControlPoints(geometry, 8);

    if (controls.length < 2) {
      setMessage("This GPX route has too few points to convert.");
      return;
    }

    loadedDraftRef.current = false;
    setIsImportedEditRoute(false);
    setGpxGeometryLocked(false);
    setPointsPayload(makeRoutePointPayload(controls, "gpx-converted-edit-control-points"));
    setRoutedPayload({
      ...(routedPayload || {}),
      points: geometry,
      waypoints: controls,
      control_points: controls,
      source: "gpx-converted-edit",
      edited_at: new Date().toISOString(),
    });
    setMessage("GPX converted to an editable route. Move the control points to reshape it.");
  }

  function undoPoint() {
    handlePointsChange(points.slice(0, -1));
  }

  function clearRoute() {
    setPointsPayload(null);
    setRoutedPayload(null);
    setGpxGeometryLocked(false);
    setIsImportedEditRoute(false);
    loadedDraftRef.current = false;
    setMessage("");
  }

  function closeLoop() {
    if (points.length < 3) {
      setMessage("Add at least three points before closing the loop.");
      return;
    }

    const first = points[0];
    const last = points[points.length - 1];
    if (first.lat === last.lat && first.lon === last.lon) {
      setMessage("This route is already closed.");
      return;
    }

    handlePointsChange([...points, { ...first }]);
  }

  function useCurrentLocation() {
    if (currentLocation?.lat && currentLocation?.lon) {
      setTargetLocation({ ...currentLocation, selectedAt: Date.now(), zoom: 15 });
      return;
    }

    requestCurrentLocation({ focus: true, quiet: false });
  }

  function downloadGpx() {
    const exportPoints = normalizeRoutePoints(routedPayload?.points?.length ? routedPayload.points : activeRoutePayload);
    if (exportPoints.length < 2) {
      setMessage("Add at least two routepoints before downloading GPX.");
      return;
    }

    const safeTitle = (title?.trim() || defaultTitle(sportId)).replace(/[^a-z0-9-_]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase() || "endurance-route";
    const blob = new Blob([routePointsToGpx(exportPoints, title?.trim() || defaultTitle(sportId))], { type: "application/gpx+xml" });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${safeTitle}.gpx`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.setTimeout(() => window.URL.revokeObjectURL(url), 400);
  }

  async function resolveEndpointLabels(routePayload) {
    const safePoints = normalizeRoutePoints(routePayload?.points);
    const firstPoint = safePoints[0];
    const lastPoint = safePoints[safePoints.length - 1];

    const [start, finish] = await Promise.all([
      routePayload?.start_location_label || routePayload?.start_location ? Promise.resolve(cleanHumanLocationLabel(routePayload.start_location_label || routePayload.start_location)) : resolveHumanLocationLabelFromCoordinates(firstPoint),
      routePayload?.finish_location_label || routePayload?.finish_location ? Promise.resolve(cleanHumanLocationLabel(routePayload.finish_location_label || routePayload.finish_location)) : resolveHumanLocationLabelFromCoordinates(lastPoint),
    ]);

    return { start: cleanHumanLocationLabel(start), finish: cleanHumanLocationLabel(finish) };
  }

  async function continueToDetails() {
    const sourcePayload = routedPayload?.points?.length ? routedPayload : makeRoutePointPayload(points);
    const safeRoutePoints = buildSafeRoutePayload(sourcePayload, points, points);

    if (normalizeRoutePoints(safeRoutePoints.points).length < 2) {
      setMessage("Add at least two routepoints before continuing.");
      return;
    }

    try {
      setMessage(editRouteId ? "Saving route..." : "Preparing route details...");
      const endpointLabels = await resolveEndpointLabels(safeRoutePoints);
      const routePointsWithLabels = {
        ...safeRoutePoints,
        start_location_label: endpointLabels.start || safeRoutePoints.start_location_label || safeRoutePoints.start_location || "",
        finish_location_label: endpointLabels.finish || safeRoutePoints.finish_location_label || safeRoutePoints.finish_location || "",
        start_location: endpointLabels.start || safeRoutePoints.start_location || "",
        finish_location: endpointLabels.finish || safeRoutePoints.finish_location || "",
      };
      const routeMetrics = calculateRouteMetrics(routePointsWithLabels.points);
      const shouldKeepAutoTitle = !titleEditedManually;
      const generatedTitle = shouldKeepAutoTitle
        ? buildAutomaticRouteTitle({ startLocation: routePointsWithLabels.start_location_label || routeStartLocation, distanceKm: routeMetrics.distance_km, sportId })
        : "";
      const finalTitle = generatedTitle || title?.trim() || defaultTitle(sportId);

      if (editRouteId) {
        const { error } = await supabase
          .from("routes")
          .update({
            title: finalTitle,
            title_is_auto: shouldKeepAutoTitle,
            route_points: routePointsWithLabels,
            distance_km: routeMetrics.distance_km || null,
            elevation_gain_m: routeMetrics.elevation_gain_m || 0,
            updated_at: new Date().toISOString(),
          })
          .eq("id", editRouteId);

        if (error) throw error;
        window.sessionStorage.removeItem("endurance_route_edit_draft");
        router.push(editReturnTo || `/routes/${editRouteId}`);
        return;
      }

      const draft = {
        sport_id: sportId,
        title: finalTitle,
        title_is_auto: shouldKeepAutoTitle,
        description: "",
        method: "draw",
        distance_km: routeMetrics.distance_km || routePointsWithLabels.distance_km || null,
        elevation_gain_m: routeMetrics.elevation_gain_m || routePointsWithLabels.elevation_gain_m || 0,
        route_points: routePointsWithLabels,
        created_by: profile?.id || null,
        saved_at: new Date().toISOString(),
      };

      window.sessionStorage.setItem("endurance_route_draft", JSON.stringify(draft));
      window.localStorage.setItem("endurance_route_draft_backup", JSON.stringify(draft));
      const params = new URLSearchParams(window.location.search);
      const detailsParams = new URLSearchParams({ routeDraft: "1" });
      const returnTo = params.get("returnTo");
      const step = params.get("step");
      if (returnTo) detailsParams.set("returnTo", returnTo);
      if (step) detailsParams.set("step", step);
      window.location.assign(`/routes/new?${detailsParams.toString()}`);
    } catch (error) {
      console.error("Could not save route", error);
      setMessage(error?.message || "Could not save route.");
    }
  }

  if (checking) {
    return (
      <main className="route-draw-fullscreen">
        <div className="route-draw-loading">Opening fullscreen editor...</div>
      </main>
    );
  }

  return (
    <main className="route-draw-fullscreen route-draw-polished route-draw-immersive">
      <section className="route-draw-topbar">
        <button type="button" className="route-draw-round-btn" onClick={() => router.push(editReturnTo || "/routes/new")} aria-label="Close draw editor">
          ←
        </button>

        <div className="route-draw-title-block route-draw-title-block-single route-draw-title-block-two-line">
          <textarea
            value={title}
            rows={2}
            onChange={(event) => {
              setTitleEditedManually(true);
              setTitle(event.target.value);
            }}
            aria-label="Route title"
          />
        </div>

        <button type="button" className="route-draw-save-btn" onClick={continueToDetails} disabled={!canContinue}>
          {editRouteId ? "Save route" : "Save & continue"}
        </button>
      </section>

      {isImportedEditRoute && gpxGeometryLocked ? (
        <section className="route-gpx-lightweight-banner">
          <div>
            <strong>GPX lightweight edit</strong>
            <span>Full route is displayed as one fast read-only line.</span>
          </div>
          <button type="button" onClick={convertGpxToEditableRoute}>Convert to editable</button>
        </section>
      ) : null}

      <RouteDrawMap
        points={points}
        routedPoints={routedPoints.length ? routedPoints : points}
        performanceMode={mapPerformanceMode}
        readOnlyGeometry={isImportedEditRoute && gpxGeometryLocked}
        onChange={handlePointsChange}
        height="100vh"
        title={title || "Draw route"}
        insertMode={false}
        layer="standard"
        routeMode={routedPoints.length ? "routed" : "drawn"}
        currentLocation={currentLocation}
        focusCurrentLocation={!points.length && !loadedDraftRef.current}
        targetLocation={targetLocation}
        onTargetLocationHandled={() => setTargetLocation(null)}
      />

      <section className="route-draw-bottom-hud route-draw-bottom-hud-final route-draw-bottom-hud-elevation-only" aria-label="Route elevation">
        <div className="route-draw-hud-metrics route-draw-hud-metrics-final route-draw-hud-metrics-elevation-only">
          <div>
            <i className="route-hud-icon route-hud-elevation" aria-hidden="true"></i>
            <span>Elevation</span>
            <b>{metrics.elevation_gain_m || 0} m+</b>
          </div>
        </div>
      </section>

      <section className="route-draw-tip">
        {isImportedEditRoute && gpxGeometryLocked ? "GPX lightweight mode · convert only if you want to reshape the route" : "Tap map to add points · drag points to reshape"}
      </section>

      <section className="route-editor-control-layer" aria-label="Route editor controls">
        <div className="route-editor-left-rail route-editor-left-rail-labeled route-editor-left-rail-compact" aria-label="Route tools">
          <button type="button" onClick={useCurrentLocation} aria-label="Current Location">
            <b>⌖</b><span>Current<br />Location</span>
          </button>
          <button type="button" onClick={closeLoop} disabled={points.length < 3 || gpxGeometryLocked} aria-label="Loop">
            <b>◌</b><span>Loop</span>
          </button>
          <button type="button" onClick={undoPoint} disabled={!points.length || gpxGeometryLocked} aria-label="Undo">
            <b>↶</b><span>Undo</span>
          </button>
          <button type="button" onClick={clearRoute} disabled={!points.length && !routedPoints.length} aria-label="Clear">
            <b className="route-tool-danger">⌫</b><span>Clear</span>
          </button>
          <button type="button" onClick={downloadGpx} disabled={!canContinue} aria-label="Download GPX">
            <b>⇩</b><span>GPX</span>
          </button>
        </div>
      </section>

      {message ? <section className="route-draw-toast">{message}</section> : null}
    </main>
  );
}
