// components/routes/FullscreenRouteDrawPage.js
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import RouteDrawMap from "./RouteDrawMap";
import { supabase } from "../../lib/supabase";
import { getSportLabel } from "../../lib/trainingHelpers";
import { calculateRouteMetrics, normalizeRoutePoints } from "../../lib/routeMetrics";
import { buildRouteGeometryInsert, inferRouteSourceType } from "../../lib/routeData";
import useRouteDrawEngine from "../../hooks/useRouteDrawEngine";
import {
  buildAutomaticRouteTitle,
  cleanHumanLocationLabel,
  cleanRouteLocationName,
  formatRouteDistanceLabel,
  isAutoGeneratedRouteTitle,
  isPlaceholderRouteTitle,
} from "../../lib/routes/routeTitleHelpers";
import {
  resolveHumanLocationLabelFromCoordinates,
  resolvePlaceNameFromCoordinates,
} from "../../lib/routes/routeGeocodeHelpers";
import { downloadTextFile, routePointsToGpx } from "../../lib/routes/gpxHelpers";
import {
  buildFullGeometryRoutePayload,
  buildSafeDraftRoutePayload,
  compactControlPoints,
  compactRoutePoints,
  makeRouteDraft,
  makeRoutePointPayload,
  routePayloadFromGeometry,
  safeReadEditDraft,
} from "../../lib/routes/fullscreenRouteDraftHelpers";

function defaultTitle(sportId) {
  return `${getSportLabel(sportId || "running")} Route`;
}

function nearestGeometryIndex(target, geometry) {
  const points = normalizeRoutePoints(geometry);
  const needle = normalizeRoutePoints([target])[0];

  if (!needle || !points.length) return -1;

  let bestIndex = -1;
  let bestDistance = Infinity;

  points.forEach((point, index) => {
    const distance = Math.hypot(Number(point.lat) - Number(needle.lat), Number(point.lon) - Number(needle.lon));
    if (distance < bestDistance) {
      bestDistance = distance;
      bestIndex = index;
    }
  });

  return bestIndex;
}

const MAP_STYLE_OPTIONS = [
  { id: "standard", name: "Standard", provider: "OpenStreetMap", description: "Clear everyday map with streets and parks.", icon: "🗺️" },
  { id: "minimal", name: "Minimal", provider: "Carto Positron", description: "Clean light map for running and city routes.", icon: "◻️" },
  { id: "outdoor", name: "Outdoor", provider: "OpenTopoMap", description: "Terrain, paths and contours for trail and hiking.", icon: "⛰️" },
  { id: "cycling", name: "Cycling", provider: "CyclOSM", description: "Cycle-friendly map with cycling infrastructure.", icon: "🚴" },
  { id: "satellite", name: "Satellite", provider: "Esri World Imagery", description: "Aerial view for forests, fields and landmarks.", icon: "🛰️" },
  { id: "dark", name: "Dark", provider: "Carto Dark Matter", description: "Low-glare dark map for evening planning.", icon: "🌙" },
];

function defaultMapStyleForSport() {
  return "standard";
}

function ElevationMiniStrip({ points = [] }) {
  const normalized = normalizeRoutePoints(points);
  const elevationPoints = normalized.filter((point) => Number.isFinite(Number(point.ele)));

  if (normalized.length < 2) return null;

  const values = elevationPoints.length >= 2
    ? normalized.map((point) => Number.isFinite(Number(point.ele)) ? Number(point.ele) : null)
    : normalized.map((_, index) => Math.sin((index / Math.max(1, normalized.length - 1)) * Math.PI) * 0.25 + 0.5);

  const numericValues = values.filter((value) => Number.isFinite(Number(value)));
  const min = Math.min(...numericValues);
  const max = Math.max(...numericValues);
  const range = Math.max(1, max - min);
  const width = 220;
  const height = 38;

  const path = values
    .map((value, index) => {
      const safe = Number.isFinite(Number(value)) ? Number(value) : min;
      const x = (index / Math.max(1, values.length - 1)) * width;
      const y = height - 5 - ((safe - min) / range) * (height - 10);
      return `${index === 0 ? "M" : "L"}${x.toFixed(1)} ${y.toFixed(1)}`;
    })
    .join(" ");

  return (
    <section className="route-draw-elevation-mini" aria-label="Elevation preview">
      <span>Elevation</span>
      <svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" aria-hidden="true">
        <path d={`${path} L ${width} ${height} L 0 ${height} Z`} className="fill" />
        <path d={path} className="line" />
      </svg>
    </section>
  );
}

function metersToPercentMap(summary = {}) {
  const entries = Object.entries(summary || {}).map(([label, meters]) => [label, Number(meters || 0)]);
  const total = entries.reduce((sum, [, meters]) => sum + meters, 0);

  if (!total) return [];

  return entries
    .filter(([, meters]) => meters > 0)
    .map(([label, meters]) => ({ label, meters, percent: Math.round((meters / total) * 100) }))
    .sort((a, b) => b.meters - a.meters);
}

function getRouteQuality(payload = {}, sportId = "") {
  const quality = payload?.route_quality;
  if (!quality) return null;

  const surfaceQuality = quality.surface_quality || {};
  const pavedRatio = Number(surfaceQuality.ideal_ratio || 0) + Number(surfaceQuality.acceptable_ratio || 0);
  const unsuitableRatio = Number(surfaceQuality.avoid_ratio || 0);
  const unknownRatio = Number(surfaceQuality.unknown_ratio || 0);
  const score = Number.isFinite(Number(quality.suitability_score))
    ? Math.max(0, Math.min(100, Math.round(Number(quality.suitability_score))))
    : Math.max(0, Math.min(100, Math.round((pavedRatio * 88) + ((1 - unsuitableRatio) * 12))));

  const warnings = [];
  const key = String(sportId || quality.sport_id || "").toLowerCase();

  if (["running", "road_cycling", "roadcycling"].includes(key) && unsuitableRatio >= 0.18) {
    warnings.push("Contains a lot of unpaved surface for this sport.");
  }

  if (["trail_running", "trailrunning", "mountain_biking", "mtb", "gravel", "gravel_cycling"].includes(key) && pavedRatio >= 0.75) {
    warnings.push("This route is quite paved for the selected sport.");
  }

  if (unknownRatio >= 0.35) {
    warnings.push("A large part of the surface is unknown in OSM/ORS data.");
  }

  return {
    score,
    pavedPercent: Math.round(pavedRatio * 100),
    unsuitablePercent: Math.round(unsuitableRatio * 100),
    unknownPercent: Math.round(unknownRatio * 100),
    detourFactor: Number(quality.detour_factor || 1),
    candidates: Number(quality.candidates_considered || 0),
    surfaces: metersToPercentMap(quality.surfaces).slice(0, 4),
    waytypes: metersToPercentMap(quality.waytypes).slice(0, 4),
    candidateSegments: Array.isArray(quality.candidate_segments) ? quality.candidate_segments : [],
    warnings,
  };
}

function humanizeRouteLabel(value = "") {
  return String(value || "unknown")
    .replace(/_/g, " ")
    .replace(/\w/g, (char) => char.toUpperCase());
}

function percentFromMap(map = {}, key = "") {
  const value = Number(map?.[key] || 0);
  return Number.isFinite(value) ? value : 0;
}

function compactPercentList(map = {}, keys = []) {
  return keys
    .map((key) => [key, percentFromMap(map, key)])
    .filter(([, value]) => value > 0)
    .map(([key, value]) => `${humanizeRouteLabel(key)} ${Math.round(value)}%`)
    .join(" · ");
}

function CandidateDebugPanel({ candidateSegments = [] }) {
  const segments = Array.isArray(candidateSegments) ? candidateSegments.slice(0, 4) : [];
  if (!segments.length) return null;

  return (
    <div className="route-quality-candidates">
      <small>ORS candidates debug</small>
      {segments.map((segment) => (
        <div className="route-quality-candidate-segment" key={`candidate-segment-${segment.segment_index}`}>
          <p>
            <span>Segment {Number(segment.segment_index) + 1}</span>
            <b>{segment.selected_score ?? "—"}/100 · {Number(segment.selected_detour || 1).toFixed(2)}×</b>
          </p>
          {segment.debug ? (
            <div className="route-quality-debug-requests">
              <em>
                mode {segment.debug.mode || "—"} · requests {segment.debug.request_count ?? 0} · candidates {segment.debug.candidate_count_after_filter ?? 0}
              </em>
              {(segment.debug.requests || []).slice(0, 5).map((request, requestIndex) => (
                <em key={`debug-request-${segment.segment_index}-${requestIndex}`}>
                  #{requestIndex + 1} {request.profile}/{request.preference} · status {request.status ?? "—"} · features {request.feature_count ?? 0} · candidates {request.candidate_count ?? 0} · points {(request.geometry_points || []).join(",") || "—"}{request.error ? ` · ${String(request.error).slice(0, 80)}` : ""}
                </em>
              ))}
            </div>
          ) : null}
          {(segment.candidates || []).slice(0, 4).map((candidate, index) => {
            const surfaces = compactPercentList(candidate.surfaces, ["effective_paved", "inferred_paved_unknown", "asphalt", "paved", "concrete", "unknown", "dirt", "ground", "mud", "sand", "gravel", "unpaved"]);
            const waytypes = compactPercentList(candidate.waytypes, ["street", "footway", "cycleway", "path", "track", "suspicious_track_path", "road", "state_road"]);

            return (
              <div className="route-quality-candidate" key={`candidate-${segment.segment_index}-${index}`}>
                <p>
                  <span>#{index + 1} {candidate.profile}/{candidate.preference}</span>
                  <b>{candidate.score ?? "—"}/100 · {Number(candidate.detour || 1).toFixed(2)}×</b>
                </p>
                <em>{surfaces || "No surface data"}</em>
                <em>{waytypes || "No waytype data"}</em>
              </div>
            );
          })}
        </div>
      ))}
    </div>
  );
}


function RouteQualityPanel({ payload, sportId, onClose }) {
  const quality = getRouteQuality(payload, sportId);

  if (!quality) return null;

  return (
    <section className="route-quality-panel-expanded" aria-label="Route quality">
      <div className="route-quality-panel-header">
        <span>◎</span>
        <strong>Route quality</strong>
        <b>{quality.score}/100</b>
        <button type="button" onClick={onClose} aria-label="Close route quality">×</button>
      </div>

      <div className="route-quality-grid">
        <div><span>Paved / suitable</span><b>{quality.pavedPercent}%</b></div>
        <div><span>Unsuitable</span><b>{quality.unsuitablePercent}%</b></div>
        <div><span>Unknown</span><b>{quality.unknownPercent}%</b></div>
        <div><span>Detour</span><b>{quality.detourFactor.toFixed(2)}×</b></div>
      </div>

      {quality.warnings.length ? (
        <div className="route-quality-warning">{quality.warnings[0]}</div>
      ) : (
        <div className="route-quality-ok">Looks suitable for {getSportLabel(sportId || "running")}.</div>
      )}

      <div className="route-quality-breakdown">
        <div>
          <small>Surface</small>
          {quality.surfaces.length ? quality.surfaces.map((item) => (
            <p key={`surface-${item.label}`}><span>{humanizeRouteLabel(item.label)}</span><b>{item.percent}%</b></p>
          )) : <p><span>Unknown</span><b>—</b></p>}
        </div>
        <div>
          <small>Waytype</small>
          {quality.waytypes.length ? quality.waytypes.map((item) => (
            <p key={`waytype-${item.label}`}><span>{humanizeRouteLabel(item.label)}</span><b>{item.percent}%</b></p>
          )) : <p><span>Unknown</span><b>—</b></p>}
        </div>
      </div>

      <CandidateDebugPanel candidateSegments={quality.candidateSegments} />
    </section>
  );
}


export default function FullscreenRouteDrawPage() {
  const router = useRouter();
  const loadedDraftRef = useRef(false);
  const currentLocationRequestedRef = useRef(false);
  const draftSavedMessageTimerRef = useRef(null);
  const routeStartLookupRef = useRef("");

  const [profile, setProfile] = useState(null);
  const [sportId, setSportId] = useState("");
  const [title, setTitle] = useState("Draw Route");
  const [drawInsertMode, setDrawInsertMode] = useState(false);
  const [drawLayer, setDrawLayer] = useState("standard");
  const [message, setMessage] = useState("");
  const [checking, setChecking] = useState(true);
  const [showPointPanel, setShowPointPanel] = useState(false);
  const [showElevationPanel, setShowElevationPanel] = useState(false);
  const [showQualityPanel, setShowQualityPanel] = useState(false);
  const [currentLocation, setCurrentLocation] = useState(null);
  const [routeStartLocation, setRouteStartLocation] = useState("Locatie bepalen");
  const [titleEditedManually, setTitleEditedManually] = useState(false);
  const [searchText, setSearchText] = useState("");
  const [searchResults, setSearchResults] = useState([]);
  const [searching, setSearching] = useState(false);
  const [targetLocation, setTargetLocation] = useState(null);
  const [searchOpen, setSearchOpen] = useState(false);
  const [editRouteId, setEditRouteId] = useState("");
  const [editReturnTo, setEditReturnTo] = useState("");
  const [nativeEditStatus, setNativeEditStatus] = useState("idle");

  const routeEngine = useRouteDrawEngine({ sportId });
  const {
    controlPoints,
    routePayload: routedPayload,
    routingStatus,
    routingError,
    setControlPoints: setEngineControlPoints,
    setRoutePayload: setEngineRoutePayload,
    loadRoute: loadEngineRoute,
    resetRoute: resetEngineRoute,
    syncSegments: syncEngineSegments,
  } = routeEngine;

  const points = controlPoints;
  const pointsPayload = useMemo(() => makeRoutePointPayload(points), [points]);
  const routedPoints = useMemo(() => normalizeRoutePoints(routedPayload), [routedPayload]);
  const activeRoutePayload = routedPayload || pointsPayload;
  const routeQuality = useMemo(() => getRouteQuality(routedPayload || activeRoutePayload, sportId), [routedPayload, activeRoutePayload, sportId]);
  const metrics = useMemo(() => calculateRouteMetrics(activeRoutePayload), [activeRoutePayload]);
  const canContinue = points.length >= 2;
  // route-start-location-reverse-lookup
  useEffect(() => {
    const firstPoint = points[0] || routedPoints[0];

    if (!firstPoint) {
      routeStartLookupRef.current = "";
      if (!titleEditedManually) {
        setRouteStartLocation("Locatie bepalen");
      }
      return;
    }

    const lat = Number(firstPoint.lat);
    const lon = Number(firstPoint.lon);

    if (!Number.isFinite(lat) || !Number.isFinite(lon)) return;

    const key = `${lat.toFixed(5)},${lon.toFixed(5)}`;

    if (routeStartLookupRef.current === key) return;

    routeStartLookupRef.current = key;

    let cancelled = false;

    resolvePlaceNameFromCoordinates({ lat, lon }).then((placeName) => {
      if (cancelled) return;

      if (placeName) {
        setRouteStartLocation(placeName);
      }
    });

    return () => {
      cancelled = true;
    };
  }, [points, routedPoints, titleEditedManually]);

  useEffect(() => {
    async function bootstrap() {
      setChecking(true);

      try {
        const params = new URLSearchParams(window.location.search);
        const editDraft = safeReadEditDraft();
        const routeEditMode = params.get("editMode") || editDraft?.edit_mode || editDraft?.route_points?.edit_mode || "";
        const shouldOpenNativeGeometryEdit = routeEditMode !== "draw" && Boolean(editDraft?.route_points?.points?.length);
        const draftRouteId = editDraft?.edit_route_id || params.get("routeId") || "";
        const draftReturnTo = editDraft?.return_to || params.get("returnTo") || (draftRouteId ? `/routes/${draftRouteId}` : "");
        setEditRouteId(draftRouteId);
        setEditReturnTo(draftReturnTo);
        const initialSport = params.get("sport_id") || editDraft?.sport_id;

        if (!initialSport) {
          router.replace("/routes/new");
          return;
        }

        const draftTitleIsAuto = editDraft?.title_is_auto !== false || isAutoGeneratedRouteTitle(editDraft?.title, initialSport);
        setTitleEditedManually(!draftTitleIsAuto);

        setSportId(initialSport);
        setDrawLayer((current) => current || defaultMapStyleForSport(initialSport));
        if (!editDraft?.route_points?.points?.length) {
          setDrawLayer(defaultMapStyleForSport(initialSport));
        }
        setTitle(editDraft?.title || defaultTitle(initialSport));

        if (editDraft?.route_points?.points?.length) {
          // Reopen Map Editor for normal drawn routes must stay in draw mode.
          // Native geometry edit mode is only for GPX/existing geometry editing.
          loadedDraftRef.current = shouldOpenNativeGeometryEdit;
          const geometry = normalizeRoutePoints(editDraft.route_points.points);
          const savedWaypoints = normalizeRoutePoints(editDraft.route_points.waypoints || editDraft.route_points.control_points);
          const editableControlPoints = savedWaypoints.length >= 2
            ? savedWaypoints
            : compactControlPoints(geometry);

          loadEngineRoute({
            controlPoints: editableControlPoints,
            routePayload: {
              ...editDraft.route_points,
              source: editDraft.route_points?.source || (shouldOpenNativeGeometryEdit ? "gpx-native-edit" : "draw-reopen-map-editor"),
              edit_mode: shouldOpenNativeGeometryEdit ? "native" : "draw",
              points: geometry,
              waypoints: editableControlPoints,
              control_points: editableControlPoints,
              point_count: geometry.length,
            },
            status: "done",
          });
          setMessage("");
          window.sessionStorage.removeItem("endurance_route_edit_draft");
        }

        const { data } = await supabase.auth.getUser();
        const user = data?.user;

        if (!user?.id) {
          router.replace("/login");
          return;
        }

        const { data: profileRow, error } = await supabase
          .from("profiles")
          .select("id,name,email,avatar_url,role,onboarding_completed,blocked")
          .eq("id", user.id)
          .maybeSingle();

        if (error) throw error;

        if (!profileRow?.onboarding_completed) {
          router.replace("/onboarding");
          return;
        }

        if (profileRow?.blocked) {
          setMessage("Your account is blocked. Contact an administrator.");
          return;
        }

        setProfile(profileRow);
      } catch (error) {
        console.error("Draw route bootstrap error", error);
        setMessage(error?.message || "Could not open draw editor.");
      } finally {
        setChecking(false);
      }
    }

    bootstrap();
  }, [router]);


  useEffect(() => {
    if (checking || !sportId) return;
    if (currentLocationRequestedRef.current) return;

    currentLocationRequestedRef.current = true;

    const shouldFocusCurrentLocation = !loadedDraftRef.current && points.length === 0 && routedPoints.length === 0;
    requestCurrentLocation({ focus: shouldFocusCurrentLocation, quiet: true });
  }, [checking, sportId, points.length, routedPoints.length]);

  function requestCurrentLocation({ focus = true, quiet = false, allowRouteFocus = false } = {}) {
    if (!navigator.geolocation) {
      if (!quiet) setMessage("Geolocation is not available on this device.");
      return;
    }

    if (!quiet) setMessage("");

    navigator.geolocation.getCurrentPosition(
      (position) => {
        const location = {
          lat: Number(position.coords.latitude.toFixed(6)),
          lon: Number(position.coords.longitude.toFixed(6)),
          accuracy: Math.round(position.coords.accuracy || 35),
          label: "Current location",
        };

        setCurrentLocation(location);

        const hasRoute = points.length >= 2 || routedPoints.length >= 2;
        const mayFocus = focus && (!loadedDraftRef.current || allowRouteFocus) && (!hasRoute || allowRouteFocus);

        if (mayFocus) {
          setTargetLocation({
            ...location,
            selectedAt: Date.now(),
            zoom: 15,
          });
        }

        if (!quiet) {
          setMessage("");
        }
      },
      () => {
        if (!quiet) setMessage("Could not access current location. You can still search or draw manually.");
      },
      { enableHighAccuracy: true, timeout: 9000, maximumAge: 60000 }
    );
  }

  async function handleNativeGeometrySegmentEdit(segmentEdit) {
    const geometry = normalizeRoutePoints(routedPayload?.points?.length ? routedPayload.points : activeRoutePayload);
    const geometryIndex = Number(segmentEdit?.geometryIndex);
    const beforeIndex = Number(segmentEdit?.beforeIndex);
    const afterIndex = Number(segmentEdit?.afterIndex);
    const editPoint = normalizeRoutePoints([segmentEdit?.editPoint])[0];

    if (geometry.length < 2 || !editPoint) {
      setMessage("Could not edit this segment.");
      return;
    }

    const targetIndex = Number.isInteger(geometryIndex)
      ? geometryIndex
      : Number.isInteger(beforeIndex) && Number.isInteger(afterIndex)
        ? Math.round((beforeIndex + afterIndex) / 2)
        : -1;

    if (targetIndex < 1 || targetIndex >= geometry.length - 1) {
      setMessage("Could not edit this part of the route.");
      return;
    }

    // Use the same logic as a newly drawn route:
    // promote the GPX geometry to a compact ordered control-point route,
    // insert the dragged shaping point at the matching position,
    // then let the central draw engine rebuild the route through segment-based /api/routes/reroute calls.
    const existingControls = normalizeRoutePoints(routedPayload?.waypoints || routedPayload?.control_points);
    const baseControls = existingControls.length >= 2
      ? existingControls
      : compactControlPoints(geometry, 14);

    if (baseControls.length < 2) {
      setMessage("Could not prepare this GPX route for routing.");
      return;
    }

    const controlGeometryIndexes = baseControls.map((point) => nearestGeometryIndex(point, geometry));
    let insertAt = 1;

    for (let index = 0; index < controlGeometryIndexes.length - 1; index += 1) {
      const currentIndex = Number(controlGeometryIndexes[index]);
      const nextIndex = Number(controlGeometryIndexes[index + 1]);

      if (Number.isFinite(currentIndex) && Number.isFinite(nextIndex) && currentIndex <= targetIndex && targetIndex <= nextIndex) {
        insertAt = index + 1;
        break;
      }

      if (Number.isFinite(currentIndex) && currentIndex < targetIndex) {
        insertAt = index + 1;
      }
    }

    insertAt = Math.max(1, Math.min(insertAt, baseControls.length));

    const previousControl = baseControls[insertAt - 1];
    const nextControl = baseControls[insertAt];
    const editIsTooCloseToExistingControl =
      [previousControl, nextControl].some((point) => {
        if (!point) return false;
        const distance = Math.hypot(Number(point.lat) - Number(editPoint.lat), Number(point.lon) - Number(editPoint.lon));
        return distance < 0.00003;
      });

    const nextControls = editIsTooCloseToExistingControl
      ? baseControls
      : [...baseControls.slice(0, insertAt), editPoint, ...baseControls.slice(insertAt)];

    try {
      setMessage("Rerouting route with the new shaping point...");

      loadedDraftRef.current = false;
      setEngineControlPoints(nextControls);

      await syncEngineSegments(nextControls, { silent: false });

      setNativeEditStatus("edited");
    } catch (error) {
      console.error("GPX promoted control-point reroute failed", error);
      setMessage(error?.message || "Could not reroute this GPX route.");
    }
  }

  function handleNativeGeometryChange(nextGeometry, meta = {}) {
    const geometry = normalizeRoutePoints(nextGeometry);

    if (geometry.length < 2) return;

    const controls = normalizeRoutePoints(routedPayload?.waypoints || routedPayload?.control_points);
    const metrics = calculateRouteMetrics(geometry);

    loadEngineRoute({
      controlPoints: controls.length >= 2 ? controls : compactControlPoints(geometry),
      routePayload: {
        ...(routedPayload && typeof routedPayload === "object" && !Array.isArray(routedPayload) ? routedPayload : {}),
        source: meta?.source || "native-gpx-geometry-edit",
        points: geometry,
        geometry_points: geometry,
        waypoints: controls,
        control_points: controls,
        point_count: geometry.length,
        distance_km: metrics.distance_km || null,
        elevation_gain_m: metrics.elevation_gain_m || 0,
        edited_at: new Date().toISOString(),
      },
      status: "done",
    });
    loadedDraftRef.current = true;
  }

  function handlePointsChange(nextPoints, meta = {}) {
    // In normal draw mode, nextPoints already are the user's real control points.
    // Do not compact/sample them here; that would change the route structure and
    // can make the editor rebuild the route from a distorted control-point set.
    const safeControlPoints = normalizeRoutePoints(nextPoints);
    loadedDraftRef.current = false;
    setEngineControlPoints(safeControlPoints, meta);
  }

  function undoPoint() {
    handlePointsChange(points.slice(0, -1));
  }

  function clearRoute() {
    resetEngineRoute();
    setDrawInsertMode(false);
    setMessage("");
    setShowPointPanel(false);
  }

  function removePoint(indexToRemove) {
    handlePointsChange(points.filter((_, index) => index !== indexToRemove));
  }

  function closeLoop() {
    if (points.length < 3) {
      setMessage("Add at least three points before closing the loop.");
      return;
    }

    const first = points[0];
    const last = points[points.length - 1];

    if (first.lat === last.lat && first.lon === last.lon) {
      setMessage("This route is already closed.");
      return;
    }

    handlePointsChange([...points, { ...first }]);
  }

  function useCurrentLocation() {
    if (currentLocation?.lat && currentLocation?.lon) {
      setTargetLocation({
        ...currentLocation,
        label: "Current location",
        selectedAt: Date.now(),
        zoom: 15,
      });
      setMessage("");
      return;
    }

    requestCurrentLocation({ focus: true, quiet: false, allowRouteFocus: true });
  }


  function buildCurrentDraft(titleOverride) {
    const isNativeGeometryDraft = loadedDraftRef.current && routedPayload?.points?.length >= 2;
    const safePayload = isNativeGeometryDraft
      ? buildFullGeometryRoutePayload(routedPayload, routedPayload.points)
      : buildSafeDraftRoutePayload(
          routedPayload?.points?.length ? routedPayload : makeRoutePointPayload(points),
          points
        );

    if (isNativeGeometryDraft) {
      const nativeControls = normalizeRoutePoints(routedPayload?.waypoints || routedPayload?.control_points);
      safePayload.waypoints = nativeControls;
      safePayload.control_points = nativeControls;
    } else {
      const drawControls = normalizeRoutePoints(controlPoints);
      const preservedControls = drawControls.length >= 2
        ? drawControls
        : compactControlPoints(points);
      safePayload.waypoints = preservedControls;
      safePayload.control_points = preservedControls;
    }
    safePayload.geometry_points = safePayload.points;
    const readableStartLocation = cleanHumanLocationLabel(routeStartLocation);
    if (readableStartLocation && !/^locatie bepalen$/i.test(readableStartLocation)) {
      safePayload.start_location_label = readableStartLocation;
      safePayload.start_location = readableStartLocation;
    }

    return makeRouteDraft({
      sportId,
      title: titleOverride || title,
      method: "draw",
      profileId: profile?.id,
      metrics,
      routePayload: safePayload,
      titleIsAuto: !titleEditedManually,
    });
  }

  async function buildTitleForPayload(routePayload, fallbackDistanceKm) {
    const safePoints = normalizeRoutePoints(routePayload?.points);
    const safeMetrics = calculateRouteMetrics(safePoints);
    const distanceKm = safeMetrics.distance_km || fallbackDistanceKm || 0;

    let place = cleanRouteLocationName(routePayload?.start_location) || cleanRouteLocationName(routeStartLocation);

    if (!place) {
      const firstPoint = safePoints[0] || points[0] || routedPoints[0];
      if (firstPoint) {
        place = await resolvePlaceNameFromCoordinates({ lat: firstPoint.lat, lon: firstPoint.lon });
        if (place) setRouteStartLocation(place);
      }
    }

    return buildAutomaticRouteTitle({
      startLocation: place,
      distanceKm,
      sportId,
    });
  }

  async function resolveCurrentEndpointLabels(routePayload) {
    const safePoints = normalizeRoutePoints(routePayload?.points);
    const firstPoint = safePoints[0] || points[0] || routedPoints[0];
    const lastPoint = safePoints[safePoints.length - 1] || points[points.length - 1] || routedPoints[routedPoints.length - 1];

    const existingStart = cleanHumanLocationLabel(routePayload?.start_location_label || routePayload?.start_location);
    const existingFinish = cleanHumanLocationLabel(routePayload?.finish_location_label || routePayload?.finish_location);

    const [resolvedStart, resolvedFinish] = await Promise.all([
      existingStart && !/^locatie bepalen$/i.test(existingStart)
        ? Promise.resolve(existingStart)
        : firstPoint
          ? resolveHumanLocationLabelFromCoordinates({ lat: firstPoint.lat, lon: firstPoint.lon })
          : Promise.resolve(""),
      existingFinish && !/^locatie bepalen$/i.test(existingFinish)
        ? Promise.resolve(existingFinish)
        : lastPoint
          ? resolveHumanLocationLabelFromCoordinates({ lat: lastPoint.lat, lon: lastPoint.lon })
          : Promise.resolve(""),
    ]);

    return {
      start: cleanHumanLocationLabel(resolvedStart || existingStart),
      finish: cleanHumanLocationLabel(resolvedFinish || existingFinish),
    };
  }

  async function getStableTitleForSave() {
    if (titleEditedManually) return title?.trim() || defaultTitle(sportId);

    const safePayload = buildSafeDraftRoutePayload(
      routedPayload?.points?.length ? routedPayload : makeRoutePointPayload(points),
      points
    );
    const generatedTitle = await buildTitleForPayload(safePayload, metrics.distance_km || routedPayload?.distance_km || pointsPayload?.distance_km || 0);

    if (generatedTitle) {
      setTitle(generatedTitle);
      return generatedTitle;
    }

    return isPlaceholderRouteTitle(title) ? defaultTitle(sportId) : title;
  }

  async function saveDraftLocally() {
    if (!canContinue) {
      setMessage("Add at least two routepoints before saving a draft.");
      return;
    }

    try {
      const stableTitle = await getStableTitleForSave();
      const draft = buildCurrentDraft(stableTitle);
      window.sessionStorage.setItem("endurance_route_draft", JSON.stringify(draft));
      window.localStorage.setItem("endurance_route_draft_backup", JSON.stringify(draft));
      setMessage("Draft saved.");

      if (draftSavedMessageTimerRef.current) {
        window.clearTimeout(draftSavedMessageTimerRef.current);
      }
      draftSavedMessageTimerRef.current = window.setTimeout(() => setMessage(""), 1200);
    } catch (error) {
      console.error("Could not save route draft", error);
      setMessage("Could not save this route draft.");
    }
  }

  function downloadGpx() {
    const exportPoints = normalizeRoutePoints(routedPayload?.points?.length ? routedPayload.points : activeRoutePayload);

    if (exportPoints.length < 2) {
      setMessage("Add at least two routepoints before downloading GPX.");
      return;
    }

    const safeTitle = (title?.trim() || defaultTitle(sportId)).replace(/[^a-z0-9-_]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase() || "endurance-route";
    const gpx = routePointsToGpx(exportPoints, title?.trim() || defaultTitle(sportId));
    downloadTextFile({ filename: `${safeTitle}.gpx`, text: gpx });
  }

  async function continueToDetails() {
    if (!canContinue) {
      setMessage("Add at least two routepoints before continuing.");
      return;
    }

    if (routingStatus === "routing") {
      setMessage("Route is still snapping to roads/paths. Wait a moment and try again.");
      return;
    }

    if (points.length >= 2 && !routedPayload?.points?.length) {
      setEngineRoutePayload(routePayloadFromGeometry(points, points, "drawn-fallback"), { status: "done" });
    }

    if (editRouteId) {
      try {
        setMessage("Saving route...");
        const activeGeometry = normalizeRoutePoints(routedPayload?.points?.length ? routedPayload.points : activeRoutePayload);
        const isNativeGeometrySave = loadedDraftRef.current && activeGeometry.length >= 2;

        const stableTitle = await getStableTitleForSave();
        const draft = buildCurrentDraft(stableTitle);
        const safeRoutePoints = isNativeGeometrySave
          ? {
              ...(routedPayload && typeof routedPayload === "object" && !Array.isArray(routedPayload) ? routedPayload : {}),
              points: activeGeometry,
              geometry_points: activeGeometry,
              point_count: activeGeometry.length,
              waypoints: normalizeRoutePoints(routedPayload?.waypoints || routedPayload?.control_points),
              control_points: normalizeRoutePoints(routedPayload?.control_points || routedPayload?.waypoints),
              source: routedPayload?.source || "native-gpx-direct-geometry-edit",
            }
          : draft.route_points;
        const normalizedRoutePoints = isNativeGeometrySave
          ? activeGeometry
          : normalizeRoutePoints(safeRoutePoints?.points);
        const normalizedWaypoints = isNativeGeometrySave
          ? normalizeRoutePoints(safeRoutePoints?.waypoints || safeRoutePoints?.control_points)
          : normalizeRoutePoints(safeRoutePoints?.waypoints || safeRoutePoints?.control_points);
        const metrics = calculateRouteMetrics(normalizedRoutePoints);
        const endpointLabels = await resolveCurrentEndpointLabels({
          ...(safeRoutePoints && typeof safeRoutePoints === "object" && !Array.isArray(safeRoutePoints) ? safeRoutePoints : {}),
          points: normalizedRoutePoints,
        });
        const shouldKeepAutoTitle = !titleEditedManually;
        const routePointsForTitle = {
          ...(safeRoutePoints && typeof safeRoutePoints === "object" && !Array.isArray(safeRoutePoints) ? safeRoutePoints : {}),
          points: normalizedRoutePoints,
          start_location_label: endpointLabels.start || safeRoutePoints?.start_location_label || safeRoutePoints?.start_location || "",
          finish_location_label: endpointLabels.finish || safeRoutePoints?.finish_location_label || safeRoutePoints?.finish_location || "",
        };
        const finalTitle = shouldKeepAutoTitle
          ? (await buildTitleForPayload(routePointsForTitle, metrics.distance_km || draft.distance_km)) || stableTitle
          : draft.title;

        const payload = {
          title: finalTitle,
          title_is_auto: shouldKeepAutoTitle,
          route_points: {
            ...(safeRoutePoints && typeof safeRoutePoints === "object" && !Array.isArray(safeRoutePoints) ? safeRoutePoints : {}),
            source: isNativeGeometrySave
              ? (safeRoutePoints?.source || "native-gpx-direct-geometry-edit")
              : (safeRoutePoints?.source || "draw-fullscreen-edit"),
            points: normalizedRoutePoints,
            waypoints: normalizedWaypoints,
            control_points: normalizedWaypoints,
            point_count: normalizedRoutePoints.length,
            start_location_label: endpointLabels.start || safeRoutePoints?.start_location_label || safeRoutePoints?.start_location || "",
            finish_location_label: endpointLabels.finish || safeRoutePoints?.finish_location_label || safeRoutePoints?.finish_location || "",
            start_location: endpointLabels.start || safeRoutePoints?.start_location || "",
            finish_location: endpointLabels.finish || safeRoutePoints?.finish_location || "",
            edited_at: new Date().toISOString(),
          },
          source_type: inferRouteSourceType("edited", safeRoutePoints),
          distance_km: metrics.distance_km || draft.distance_km || null,
          elevation_gain_m: metrics.elevation_gain_m || draft.elevation_gain_m || 0,
          updated_at: new Date().toISOString(),
        };

        const { error } = await supabase
          .from("routes")
          .update(payload)
          .eq("id", editRouteId);

        if (error) throw error;

        const geometryInsert = buildRouteGeometryInsert({
          routeId: editRouteId,
          routePoints: normalizedRoutePoints,
          sourceType: inferRouteSourceType("edited", safeRoutePoints),
        });

        if (geometryInsert.point_count >= 2) {
          const { data: existingGeometry } = await supabase
            .from("route_geometries")
            .select("id,version")
            .eq("route_id", editRouteId)
            .order("version", { ascending: false })
            .limit(1)
            .maybeSingle();

          const nextVersion = Number(existingGeometry?.version || 0) + 1;
          const { data: geometryRow, error: geometryError } = await supabase
            .from("route_geometries")
            .insert({
              ...geometryInsert,
              version: nextVersion,
              source_type: "edited",
            })
            .select("id,version")
            .single();

          if (geometryError) throw geometryError;

          if (geometryRow?.id) {
            await supabase
              .from("routes")
              .update({
                geometry_id: geometryRow.id,
                route_version: geometryRow.version || nextVersion,
              })
              .eq("id", editRouteId);
          }
        }

        window.sessionStorage.removeItem("endurance_route_edit_draft");
        router.push(editReturnTo || `/routes/${editRouteId}`);
        return;
      } catch (error) {
        console.error("Could not save edited route", error);
        setMessage(error?.message || "Could not save route.");
        return;
      }
    }

    try {
      const stableTitle = await getStableTitleForSave();
      const draft = buildCurrentDraft(stableTitle);
      window.sessionStorage.setItem("endurance_route_draft", JSON.stringify(draft));
      window.localStorage.setItem("endurance_route_draft_backup", JSON.stringify(draft));

      const params = new URLSearchParams(window.location.search);
      const detailsParams = new URLSearchParams({ routeDraft: "1" });
      const returnTo = params.get("returnTo");
      const step = params.get("step");
      if (returnTo) detailsParams.set("returnTo", returnTo);
      if (step) detailsParams.set("step", step);

      window.location.assign(`/routes/new?${detailsParams.toString()}`);
    } catch (error) {
      console.error("Could not save route draft", error);
      setMessage("Could not prepare the route details. Try again with fewer routepoints.");
    }
  }



  useEffect(() => {
    const query = searchText.trim();

    if (query.length < 2) {
      setSearchResults([]);
      return;
    }

    const timeout = window.setTimeout(async () => {
      try {
        setSearching(true);

        const response = await fetch(`/api/geocode/search?text=${encodeURIComponent(query)}`);
        const data = await response.json();

        setSearchResults(Array.isArray(data?.features) ? data.features : []);
      } catch (error) {
        console.error("Location search failed", error);
      } finally {
        setSearching(false);
      }
    }, 350);

    return () => window.clearTimeout(timeout);
  }, [searchText]);

  function flyToLocation(result) {
    const location = {
      lat: Number(result.lat),
      lon: Number(result.lon),
      label: result.label || "Selected location",
      forceFocusAt: Date.now(),
    };

    setTargetLocation(location);
    setSearchResults([]);
    setSearchText(result.label || "");
    setSearchOpen(false);
  }


  useEffect(() => {
    if (titleEditedManually) return;

    const distanceKm = metrics.distance_km || routedPayload?.distance_km || pointsPayload?.distance_km || 0;

    const generatedTitle = buildAutomaticRouteTitle({
      startLocation: routeStartLocation,
      distanceKm,
      sportId,
    });

    if (generatedTitle) {
      setTitle(generatedTitle);
    }
  }, [
    titleEditedManually,
    routeStartLocation,
    metrics.distance_km,
    routedPayload?.distance_km,
    pointsPayload?.distance_km,
    sportId,
  ]);



  function dispatchMapControl(action) {
    if (typeof window === "undefined") return;
    window.dispatchEvent(
      new CustomEvent("endurance:route-map-control", {
        detail: { action },
      })
    );
  }

  if (checking) {
    return (
      <main className="route-draw-fullscreen">
        <div className="route-draw-loading">Opening fullscreen editor...</div>
      </main>
    );
  }

  return (
    <main className="route-draw-fullscreen route-draw-polished route-draw-immersive">
      <section className="route-draw-topbar">
        <button
          type="button"
          className="route-draw-round-btn"
          onClick={() => router.push(editReturnTo || "/routes/new")}
          aria-label="Close draw editor"
        >
          ←
        </button>

        <div className="route-draw-title-block route-draw-title-block-single route-draw-title-block-two-line">
          <textarea
            value={title}
            rows={2}
            onChange={(event) => {
              setTitleEditedManually?.(true);
              setTitle(event.target.value);
            }}
            aria-label="Route title"
          />
        </div>

        <button
          type="button"
          className="route-draw-save-btn"
          onClick={continueToDetails}
          disabled={!canContinue}
        >
          {editRouteId ? "Save route" : "Save & continue"}
        </button>
      </section>

      {searchOpen ? (
        <div className="route-search-bar route-search-bar-expanded">
          <div className="route-search-input-wrap">
            <span className="route-search-icon">⌕</span>
            <input
              type="text"
              value={searchText}
              onChange={(event) => setSearchText(event.target.value)}
              placeholder="Search address, café, restaurant or place"
              autoFocus
            />
            <button
              type="button"
              className="route-search-close"
              onClick={() => {
                setSearchOpen(false);
                setSearchResults([]);
              }}
              aria-label="Close search"
            >
              ×
            </button>
          </div>

          {searchResults.length ? (
            <div className="route-search-results">
              {searchResults.map((result) => (
                <button
                  key={result.id}
                  type="button"
                  onClick={() => flyToLocation(result)}
                >
                  <b>{result.label}</b>
                  <small>
                    {Number(result.lat).toFixed(5)}, {Number(result.lon).toFixed(5)}
                  </small>
                </button>
              ))}
            </div>
          ) : null}

          {searching ? (
            <div className="route-search-loading">Searching locations...</div>
          ) : null}
        </div>
      ) : null}

      <RouteDrawMap
        points={points}
        routedPoints={routedPoints.length ? routedPoints : points}
        onChange={handlePointsChange}
        onNativeGeometrySegmentEdit={handleNativeGeometrySegmentEdit}
        onNativeGeometryChange={handleNativeGeometryChange}
        nativeGeometryEdit={loadedDraftRef.current && routedPoints.length >= 2}
        height="100vh"
        title={title || "Draw route"}
        insertMode={drawInsertMode}
        layer="standard"
        routeMode={routedPoints.length ? "routed" : "drawn"}
        currentLocation={currentLocation}
        focusCurrentLocation={!points.length && !loadedDraftRef.current}
        targetLocation={targetLocation}
        onTargetLocationHandled={() => setTargetLocation(null)}
      />
      <section className="route-draw-bottom-hud route-draw-bottom-hud-final route-draw-bottom-hud-elevation-only" aria-label="Route elevation">
        <div className="route-draw-hud-metrics route-draw-hud-metrics-final route-draw-hud-metrics-elevation-only">
          <div>
            <i className="route-hud-icon route-hud-elevation" aria-hidden="true"></i>
            <span>Elevation</span>
            <b>{metrics.elevation_gain_m || 0} m+</b>
          </div>
        </div>
      </section>


      {/* Map style picker removed: map style is selected automatically per sport. */}

      {routingError && points.length < 2 ? <section className="route-draw-routing-error">{routingError}</section> : null}

      {routedPoints.length ? (
        <section className="route-draw-routing-status">
          
        </section>
      ) : null}

      {showElevationPanel ? (
        <section className="route-elevation-panel-expanded" aria-label="Elevation profile">
          <div className="route-elevation-panel-header">
            <span>△</span>
            <strong>Elevation profile</strong>
            <button type="button" onClick={() => setShowElevationPanel(false)} aria-label="Close elevation profile">⌃</button>
          </div>
          <ElevationMiniStrip points={activeRoutePayload} />
        </section>
      ) : null}

      {showQualityPanel ? (
        <RouteQualityPanel
          payload={routedPayload || activeRoutePayload}
          sportId={sportId}
          onClose={() => setShowQualityPanel(false)}
        />
      ) : null}



      {showPointPanel ? (
        <section className="route-draw-point-panel">
          <div>
            <strong>Route points</strong>
            <button type="button" onClick={() => setShowPointPanel(false)}>×</button>
          </div>

          {points.length ? (
            points.map((point, index) => (
              <button key={`${point.lat}-${point.lon}-${index}`} type="button" onClick={() => removePoint(index)}>
                <span>{index + 1}</span>
                <small>{point.lat.toFixed(5)}, {point.lon.toFixed(5)}</small>
                <b>Remove</b>
              </button>
            ))
          ) : (
            <p>Tap on the map to add your first point.</p>
          )}
        </section>
      ) : null}

      <section className="route-draw-tip">
        Tap map to add points · tap route line to shape · drag points to reshape
      </section>


      <section className="route-editor-control-layer" aria-label="Route editor controls">

        <div className="route-editor-left-rail route-editor-left-rail-labeled route-editor-left-rail-compact" aria-label="Route tools">
          <button type="button" onClick={useCurrentLocation} aria-label="Current Location">
            <b>⌖</b><span>Current<br />Location</span>
          </button>
          <button type="button" onClick={() => setSearchOpen((value) => !value)} className={searchOpen ? "active" : ""} aria-label="Search">
            <b>⌕</b><span>Search</span>
          </button>
          <button type="button" onClick={closeLoop} disabled={points.length < 3} aria-label="Loop">
            <b>◌</b><span>Loop</span>
          </button>
          <button type="button" onClick={undoPoint} disabled={!points.length} aria-label="Undo">
            <b>↶</b><span>Undo</span>
          </button>
          <button type="button" onClick={clearRoute} disabled={!points.length} aria-label="Clear">
            <b className="route-tool-danger">⌫</b><span>Clear</span>
          </button>
          <button type="button" onClick={() => setShowQualityPanel((value) => !value)} className={showQualityPanel ? "active" : ""} disabled={!routeQuality} aria-label="Route quality">
            <b>◎</b><span>Quality</span>
          </button>
          <button type="button" onClick={() => setShowElevationPanel((value) => !value)} className={showElevationPanel ? "active" : ""} aria-label="Elevation profile">
            <b>△</b><span>Elevation</span>
          </button>
        </div>


</section>

      {message ? <section className="route-draw-toast">{message}</section> : null}
    </main>
  );
}
