// components/routes/FullscreenRouteDrawPage.js
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import RouteDrawMap from "./RouteDrawMap";
import { supabase } from "../../lib/supabase";
import { getSportLabel } from "../../lib/trainingHelpers";
import { calculateRouteMetrics, estimateTimeText, normalizeRoutePoints, simplifyRoutePoints } from "../../lib/routeMetrics";
import { buildRoutePayloadFromSegments, getControlSegments } from "../../lib/routes/routeSegmentEngine";
import { buildRouteGeometryInsert, inferRouteSourceType } from "../../lib/routeData";

function makeRoutePointPayload(points, source = "draw-fullscreen") {
  const normalized = normalizeRoutePoints(points);
  const metrics = calculateRouteMetrics(normalized);

  return {
    source,
    points: normalized,
    point_count: normalized.length,
    distance_km: metrics.distance_km || null,
    elevation_gain_m: metrics.elevation_gain_m || 0,
    elevation_loss_m: metrics.elevation_loss_m || 0,
    max_elevation_m: metrics.max_elevation_m || null,
    drawn_at: new Date().toISOString(),
  };
}

function defaultTitle(sportId) {
  return `${getSportLabel(sportId || "running")} Route`;
}

function pickPlaceNameFromLabel(value) {
  const raw = String(value || "").trim();
  if (!raw) return "";
  const parts = raw.split(",").map((part) => part.trim()).filter(Boolean).filter((part) => !/^(netherlands|nederland)$/i.test(part));
  const postalCodeIndex = parts.findIndex((part) => /\b\d{4}\s?[A-Z]{2}\b/i.test(part));
  if (postalCodeIndex >= 0 && parts[postalCodeIndex + 1]) return parts[postalCodeIndex + 1];
  const likelyPlace = parts.find((part) => !/^(street|road|route|unnamed|current location|startlocatie)$/i.test(part) && !/\d/.test(part));
  return likelyPlace || parts[0] || "";
}

function cleanRouteLocationName(value) {
  const place = pickPlaceNameFromLabel(value);

  if (!place || /^(locatie bepalen|startlocatie|current location)$/i.test(place)) {
    return "";
  }

  return place;
}

function formatRouteDistanceLabel(value) {
  const distance = Number(value);
  if (!Number.isFinite(distance) || distance <= 0) return "0.0 km";
  return `${distance.toFixed(1)} km`;
}

function buildAutomaticRouteTitle({ startLocation, distanceKm, sportId }) {
  const location = cleanRouteLocationName(startLocation);
  const distance = Number(distanceKm);

  if (!location || !Number.isFinite(distance) || distance <= 0) {
    return "";
  }

  return `${location} - ${formatRouteDistanceLabel(distance)} - ${getSportLabel(sportId || "running")}`;
}

function isPlaceholderRouteTitle(value) {
  const raw = String(value || "").trim();
  return !raw || /^locatie bepalen\s*-/i.test(raw) || /^route\s*-\s*0(?:\.0)?\s*km\s*-/i.test(raw);
}

function isAutoGeneratedRouteTitle(value, sportId) {
  const raw = String(value || "").trim();
  if (!raw) return true;
  if (isPlaceholderRouteTitle(raw)) return true;

  const sportLabel = getSportLabel(sportId || "running").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const autoPattern = new RegExp(`^.+\\s-\\s\\d+(?:[.,]\\d+)?\\s?km\\s-\\s${sportLabel}$`, "i");

  return autoPattern.test(raw);
}



function cleanHumanLocationLabel(value) {
  return String(value || "")
    .trim()
    .replace(/,?\s*(Nederland|Netherlands)\s*$/i, "")
    .replace(/\s{2,}/g, " ")
    .trim();
}

function pickHumanLocationLabel(data) {
  return cleanHumanLocationLabel(
    data?.label ||
    data?.name ||
    data?.display_name ||
    data?.place ||
    data?.city ||
    data?.town ||
    data?.village ||
    data?.municipality ||
    data?.locality ||
    data?.county ||
    ""
  );
}

async function resolveHumanLocationLabelFromCoordinates({ lat, lon }) {
  const safeLat = Number(lat);
  const safeLon = Number(lon);

  if (!Number.isFinite(safeLat) || !Number.isFinite(safeLon)) return "";

  try {
    const response = await fetch(`/api/geocode/reverse?lat=${encodeURIComponent(safeLat)}&lon=${encodeURIComponent(safeLon)}`);

    if (!response.ok) return "";

    const data = await response.json();
    return pickHumanLocationLabel(data);
  } catch (error) {
    console.warn("Could not resolve route endpoint location", error);
    return "";
  }
}

async function resolvePlaceNameFromCoordinates({ lat, lon }) {
  const safeLat = Number(lat);
  const safeLon = Number(lon);

  if (!Number.isFinite(safeLat) || !Number.isFinite(safeLon)) return "";

  try {
    const response = await fetch(`/api/geocode/reverse?lat=${encodeURIComponent(safeLat)}&lon=${encodeURIComponent(safeLon)}`);

    if (!response.ok) return "";

    const data = await response.json();

    return cleanRouteLocationName(
      data?.place ||
      data?.city ||
      data?.town ||
      data?.village ||
      data?.municipality ||
      data?.locality ||
      data?.county ||
      data?.label ||
      data?.display_name ||
      ""
    );
  } catch (error) {
    console.warn("Could not resolve route start location", error);
    return "";
  }
}



function compactRoutePoints(points, maxPoints = 900) {
  const normalized = normalizeRoutePoints(points);
  const simplified = simplifyRoutePoints(normalized, normalized.length > 350 ? 6 : 2.5);

  if (simplified.length <= maxPoints) return simplified;

  const step = Math.ceil(simplified.length / maxPoints);
  const compacted = simplified.filter((_, index) => index % step === 0);
  const last = simplified[simplified.length - 1];

  if (last && compacted[compacted.length - 1] !== last) {
    compacted.push(last);
  }

  return compacted;
}

function sampleEvenlyAcrossRoute(points, maxPoints = 18) {
  const normalized = normalizeRoutePoints(points);

  if (normalized.length <= maxPoints) return normalized;
  if (maxPoints <= 2) return [normalized[0], normalized[normalized.length - 1]].filter(Boolean);

  const lastIndex = normalized.length - 1;
  const sampled = [];

  for (let index = 0; index < maxPoints; index += 1) {
    const sourceIndex = Math.round((index / (maxPoints - 1)) * lastIndex);
    const point = normalized[sourceIndex];

    if (!point) continue;

    const previous = sampled[sampled.length - 1];
    if (!previous || previous.lat !== point.lat || previous.lon !== point.lon) {
      sampled.push(point);
    }
  }

  const last = normalized[lastIndex];
  const sampledLast = sampled[sampled.length - 1];

  if (last && (!sampledLast || sampledLast.lat !== last.lat || sampledLast.lon !== last.lon)) {
    sampled.push(last);
  }

  return sampled;
}

function compactControlPoints(points, maxPoints = 18) {
  return sampleEvenlyAcrossRoute(points, maxPoints);
}

function buildSafeDraftRoutePayload(payload, fallbackPoints) {
  const payloadPoints = normalizeRoutePoints(payload);
  const fallback = normalizeRoutePoints(fallbackPoints);
  const points = compactRoutePoints(payloadPoints.length ? payloadPoints : fallback);

  return {
    source: payload?.source || "draw-fullscreen",
    profile: payload?.profile || null,
    provider_url: payload?.provider_url || null,
    waypoints: Array.isArray(payload?.waypoints) ? compactRoutePoints(payload.waypoints, 80) : [],
    points,
    point_count: points.length,
    distance_km: payload?.distance_km || null,
    elevation_gain_m: payload?.elevation_gain_m || 0,
    route_quality: payload?.route_quality || null,
    routed_at: payload?.routed_at || payload?.drawn_at || payload?.edited_at || new Date().toISOString(),
  };
}

function buildFullGeometryRoutePayload(payload, fallbackPoints = []) {
  const payloadPoints = normalizeRoutePoints(payload?.points?.length ? payload.points : payload);
  const fallback = normalizeRoutePoints(fallbackPoints);
  const points = payloadPoints.length ? payloadPoints : fallback;
  const waypoints = normalizeRoutePoints(payload?.waypoints || payload?.control_points);

  return {
    ...(payload && typeof payload === "object" && !Array.isArray(payload) ? payload : {}),
    source: payload?.source || "native-gpx-full-geometry",
    points,
    geometry_points: points,
    waypoints,
    control_points: waypoints,
    point_count: points.length,
    distance_km: payload?.distance_km || null,
    elevation_gain_m: payload?.elevation_gain_m || 0,
    route_quality: payload?.route_quality || null,
    routed_at: payload?.routed_at || payload?.drawn_at || payload?.edited_at || new Date().toISOString(),
  };
}

function nearestGeometryIndex(target, geometry) {
  const points = normalizeRoutePoints(geometry);
  const needle = normalizeRoutePoints([target])[0];

  if (!needle || !points.length) return -1;

  let bestIndex = -1;
  let bestDistance = Infinity;

  points.forEach((point, index) => {
    const distance = Math.hypot(Number(point.lat) - Number(needle.lat), Number(point.lon) - Number(needle.lon));
    if (distance < bestDistance) {
      bestDistance = distance;
      bestIndex = index;
    }
  });

  return bestIndex;
}

function mergeLocalSegmentGeometry(existingGeometry, previousControlPoints, nextControlPoints, insertAt, segmentGeometry) {
  const existing = normalizeRoutePoints(existingGeometry);
  const previous = normalizeRoutePoints(previousControlPoints);
  const next = normalizeRoutePoints(nextControlPoints);
  const segment = normalizeRoutePoints(segmentGeometry);

  if (!next.length) return [];

  const safeInsertAt = Math.max(1, Math.min(Number(insertAt) || next.length - 1, next.length - 1));
  const previousPoint = previous[safeInsertAt - 1] || next[safeInsertAt - 1];
  const nextPoint = previous[safeInsertAt] || next[safeInsertAt + 1];
  const promotedPoint = next[safeInsertAt];
  const replacement = segment.length >= 2
    ? segment
    : [previousPoint, promotedPoint, nextPoint].filter(Boolean);

  if (existing.length < 2 || !previousPoint || !nextPoint) {
    return next;
  }

  let startIndex = nearestGeometryIndex(previousPoint, existing);
  let endIndex = nearestGeometryIndex(nextPoint, existing);

  if (startIndex < 0 || endIndex < 0 || startIndex === endIndex) {
    return next;
  }

  if (startIndex > endIndex) {
    [startIndex, endIndex] = [endIndex, startIndex];
  }

  const before = existing.slice(0, startIndex);
  const after = existing.slice(endIndex + 1);
  const merged = [...before, ...replacement, ...after];

  return compactRoutePoints(merged, 900);
}

function routePayloadFromGeometry(points, waypoints, source = "local-segment-reroute") {
  const geometry = compactRoutePoints(points);
  const metrics = calculateRouteMetrics(geometry);

  return {
    source,
    points: geometry,
    waypoints: compactControlPoints(waypoints),
    control_points: compactControlPoints(waypoints),
    geometry_points: geometry,
    point_count: geometry.length,
    distance_km: metrics.distance_km || null,
    elevation_gain_m: metrics.elevation_gain_m || 0,
    elevation_loss_m: metrics.elevation_loss_m || 0,
    edited_at: new Date().toISOString(),
  };
}


function xmlEscape(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function routePointsToGpx(points, name = "Endurance Route") {
  const normalized = normalizeRoutePoints(points);
  const trackPoints = normalized
    .map((point) => {
      const ele = Number.isFinite(Number(point.ele)) ? `\n        <ele>${Number(point.ele).toFixed(1)}</ele>` : "";
      return `      <trkpt lat="${Number(point.lat).toFixed(6)}" lon="${Number(point.lon).toFixed(6)}">${ele}\n      </trkpt>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="Endurance" xmlns="http://www.topografix.com/GPX/1/1">\n  <metadata>\n    <name>${xmlEscape(name)}</name>\n    <time>${new Date().toISOString()}</time>\n  </metadata>\n  <trk>\n    <name>${xmlEscape(name)}</name>\n    <trkseg>\n${trackPoints}\n    </trkseg>\n  </trk>\n</gpx>`;
}

function downloadTextFile({ filename, text, type = "application/gpx+xml" }) {
  if (typeof window === "undefined") return;

  const blob = new Blob([text], { type });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => window.URL.revokeObjectURL(url), 400);
}

function makeRouteDraft({ sportId, title, method = "draw", profileId, metrics, routePayload, titleIsAuto = true }) {
  return {
    sport_id: sportId,
    title: title?.trim() || defaultTitle(sportId),
    title_is_auto: titleIsAuto !== false,
    description: "",
    method,
    distance_km: metrics.distance_km || routePayload.distance_km || "",
    elevation_gain_m: metrics.elevation_gain_m || routePayload.elevation_gain_m || "",
    estimated_time: estimateTimeText(metrics.distance_km || routePayload.distance_km, sportId),
    route_points: routePayload,
    created_by: profileId || null,
    saved_at: new Date().toISOString(),
  };
}


const MAP_STYLE_OPTIONS = [
  { id: "standard", name: "Standard", provider: "OpenStreetMap", description: "Clear everyday map with streets and parks.", icon: "🗺️" },
  { id: "minimal", name: "Minimal", provider: "Carto Positron", description: "Clean light map for running and city routes.", icon: "◻️" },
  { id: "outdoor", name: "Outdoor", provider: "OpenTopoMap", description: "Terrain, paths and contours for trail and hiking.", icon: "⛰️" },
  { id: "cycling", name: "Cycling", provider: "CyclOSM", description: "Cycle-friendly map with cycling infrastructure.", icon: "🚴" },
  { id: "dark", name: "Dark", provider: "Carto Dark Matter", description: "Dark performance view for night planning.", icon: "🌙" },
];

const DEFAULT_CENTER = { lat: 50.853, lon: 5.691 };

function toMapPoint(point) {
  if (!point) return null;

  const lat = Number(point.lat);
  const lon = Number(point.lon);

  if (!Number.isFinite(lat) || !Number.isFinite(lon)) return null;

  return {
    ...point,
    lat: Number(lat.toFixed(6)),
    lon: Number(lon.toFixed(6)),
  };
}

function getCenterPoint(points) {
  const normalized = normalizeRoutePoints(points);
  if (!normalized.length) return DEFAULT_CENTER;

  const sums = normalized.reduce(
    (acc, point) => ({ lat: acc.lat + point.lat, lon: acc.lon + point.lon }),
    { lat: 0, lon: 0 }
  );

  return {
    lat: Number((sums.lat / normalized.length).toFixed(6)),
    lon: Number((sums.lon / normalized.length).toFixed(6)),
  };
}


function getRouteQuality(payload, sportId = "") {
  const quality = payload?.route_quality || payload?.quality || payload?.metadata?.route_quality || null;

  if (!quality || typeof quality !== "object") return null;

  return {
    ...quality,
    sport_id: quality.sport_id || sportId || payload?.sport_id || null,
  };
}

function RouteQualityPanel({ payload, sportId, onClose }) {
  const quality = payload?.route_quality;
  if (!quality) return null;

  const surfaceQuality = quality.surface_quality || {};
  const pavedRatio = Number(surfaceQuality.ideal_ratio || 0) + Number(surfaceQuality.acceptable_ratio || 0);
  const unsuitableRatio = Number(surfaceQuality.avoid_ratio || 0);
  const unknownRatio = Number(surfaceQuality.unknown_ratio || 0);
  const score = Number.isFinite(Number(quality.suitability_score))
    ? Math.max(0, Math.min(100, Math.round(Number(quality.suitability_score))))
    : Math.max(0, Math.min(100, Math.round((pavedRatio * 88) + ((1 - unsuitableRatio) * 12))));

  const warning = (() => {
    const key = String(sportId || quality.sport_id || "").toLowerCase();
    if (["running", "road_cycling", "roadcycling"].includes(key) && unsuitableRatio >= 0.18) return "Contains a lot of unpaved surface for this sport.";
    if (["trail_running", "trailrunning", "mountain_biking", "mtb", "gravel", "gravel_cycling"].includes(key) && pavedRatio >= 0.75) return "This route is quite paved for the selected sport.";
    if (unknownRatio >= 0.35) return "A large part of the surface is unknown in OSM/ORS data.";
    return "Looks suitable for this sport.";
  })();

  return (
    <section className="route-quality-panel-expanded" aria-label="Route quality">
      <div className="route-quality-panel-header">
        <span>◎</span>
        <strong>Route quality</strong>
        <b>{score}/100</b>
        <button type="button" onClick={onClose} aria-label="Close route quality">×</button>
      </div>
      <div className="route-quality-grid">
        <div><span>Paved / suitable</span><b>{Math.round(pavedRatio * 100)}%</b></div>
        <div><span>Unsuitable</span><b>{Math.round(unsuitableRatio * 100)}%</b></div>
        <div><span>Unknown</span><b>{Math.round(unknownRatio * 100)}%</b></div>
        <div><span>Detour</span><b>{Number(quality.detour_factor || 1).toFixed(2)}×</b></div>
      </div>
      <div className={warning.startsWith("Looks") ? "route-quality-ok" : "route-quality-warning"}>{warning}</div>
    </section>
  );
}

function MapStylePanel({ value, onChange, onClose }) {
  return (
    <section className="route-map-style-panel" aria-label="Map style">
      <div className="route-map-style-header">
        <strong>Map style</strong>
        <button type="button" onClick={onClose} aria-label="Close map style panel">×</button>
      </div>
      <div className="route-map-style-options">
        {MAP_STYLE_OPTIONS.map((option) => (
          <button
            key={option.id}
            type="button"
            className={value === option.id ? "active" : ""}
            onClick={() => {
              onChange(option.id);
              onClose();
            }}
          >
            <span>{option.icon}</span>
            <div>
              <strong>{option.name}</strong>
              <small>{option.provider}</small>
              <p>{option.description}</p>
            </div>
          </button>
        ))}
      </div>
    </section>
  );
}

function ControlButton({ icon, label, onClick, danger = false, disabled = false }) {
  return (
    <button type="button" onClick={onClick} disabled={disabled} className={`route-draw-control ${danger ? "danger" : ""}`}>
      <span>{icon}</span>
      <small>{label}</small>
    </button>
  );
}

function pointsEqual(a, b) {
  return Number(a?.lat).toFixed(6) === Number(b?.lat).toFixed(6) && Number(a?.lon).toFixed(6) === Number(b?.lon).toFixed(6);
}

export default function FullscreenRouteDrawPage() {
  const router = useRouter();
  const loadedDraftRef = useRef(false);
  const currentLocationRequestedRef = useRef(false);
  const draftSavedMessageTimerRef = useRef(null);
  const routeStartLookupRef = useRef("");
  const routingAbortRef = useRef(null);
  const routingRequestIdRef = useRef(0);
  const segmentCacheRef = useRef(new Map());
  const segmentSyncIdRef = useRef(0);
  const suppressNextSegmentSyncRef = useRef(false);

  const [profile, setProfile] = useState(null);
  const [sportId, setSportId] = useState("");
  const [title, setTitle] = useState("Draw Route");
  const [pointsPayload, setPointsPayload] = useState(null);
  const [drawInsertMode, setDrawInsertMode] = useState(false);
  const [drawLayer, setDrawLayer] = useState("standard");
  const [message, setMessage] = useState("");
  const [checking, setChecking] = useState(true);
  const [showPointPanel, setShowPointPanel] = useState(false);
  const [showElevationPanel, setShowElevationPanel] = useState(false);
  const [showQualityPanel, setShowQualityPanel] = useState(false);
  const [routedPayload, setRoutedPayload] = useState(null);
  const [routeSegments, setRouteSegments] = useState([]);
  const [routingStatus, setRoutingStatus] = useState("idle");
  const [routingError, setRoutingError] = useState("");
  const [currentLocation, setCurrentLocation] = useState(null);
  const [routeStartLocation, setRouteStartLocation] = useState("Locatie bepalen");
  const [titleEditedManually, setTitleEditedManually] = useState(false);
  const [searchText, setSearchText] = useState("");
  const [searchResults, setSearchResults] = useState([]);
  const [searching, setSearching] = useState(false);
  const [targetLocation, setTargetLocation] = useState(null);
  const [searchOpen, setSearchOpen] = useState(false);
  const [editRouteId, setEditRouteId] = useState("");
  const [editReturnTo, setEditReturnTo] = useState("");
  const [nativeEditStatus, setNativeEditStatus] = useState("idle");

  const controlPoints = useMemo(() => normalizeRoutePoints(pointsPayload), [pointsPayload]);
  const routedPoints = useMemo(() => normalizeRoutePoints(routedPayload), [routedPayload]);
  const points = controlPoints;
  const activeRoutePayload = routedPayload || pointsPayload;
  const routeQuality = useMemo(() => getRouteQuality(routedPayload || activeRoutePayload, sportId), [routedPayload, activeRoutePayload, sportId]);
  const metrics = useMemo(() => calculateRouteMetrics(activeRoutePayload), [activeRoutePayload]);
  const canContinue = points.length >= 2;
  const routeSignature = useMemo(
    () => points.map((point) => `${point.lat.toFixed(6)},${point.lon.toFixed(6)}`).join("|"),
    [points]
  );

  // route-start-location-reverse-lookup
  useEffect(() => {
    const firstPoint = points[0] || routedPoints[0];

    if (!firstPoint) {
      routeStartLookupRef.current = "";
      if (!titleEditedManually) {
        setRouteStartLocation("Locatie bepalen");
      }
      return;
    }

    const lat = Number(firstPoint.lat);
    const lon = Number(firstPoint.lon);

    if (!Number.isFinite(lat) || !Number.isFinite(lon)) return;

    const key = `${lat.toFixed(5)},${lon.toFixed(5)}`;

    if (routeStartLookupRef.current === key) return;

    routeStartLookupRef.current = key;

    let cancelled = false;

    resolvePlaceNameFromCoordinates({ lat, lon }).then((placeName) => {
      if (cancelled) return;

      if (placeName) {
        setRouteStartLocation(placeName);
      }
    });

    return () => {
      cancelled = true;
    };
  }, [points, routedPoints, titleEditedManually]);

  useEffect(() => {
    if (titleEditedManually) return;

    const distance = metrics.distance_km || routedPayload?.distance_km || activeRoutePayload?.distance_km;
    const nextTitle = buildAutomaticRouteTitle({ startLocation: routeStartLocation, distanceKm: distance, sportId });

    if (nextTitle) {
      setTitle((current) => {
        if (current === nextTitle) return current;
        if (current && !isAutoGeneratedRouteTitle(current, sportId)) return current;
        return nextTitle;
      });
    }
  }, [routeStartLocation, metrics.distance_km, routedPayload?.distance_km, activeRoutePayload?.distance_km, sportId, titleEditedManually]);

  useEffect(() => {
    async function bootstrap() {
      setChecking(true);

      try {
        const params = new URLSearchParams(window.location.search);
        const draftRaw = window.sessionStorage.getItem("endurance_route_edit_draft");
        const editDraft = draftRaw ? JSON.parse(draftRaw) : null;
        const draftRouteId = editDraft?.edit_route_id || params.get("routeId") || "";
        const draftReturnTo = editDraft?.return_to || params.get("returnTo") || (draftRouteId ? `/routes/${draftRouteId}` : "");
        const initialSport = params.get("sport_id") || editDraft?.sport_id;

        if (!initialSport) {
          router.replace("/routes/new");
          return;
        }

        setSportId(initialSport);
        setEditRouteId(draftRouteId);
        setEditReturnTo(draftReturnTo);

        const draftTitle = editDraft?.title || defaultTitle(initialSport);
        setTitle(draftTitle);
        setTitleEditedManually(!(editDraft?.title_is_auto !== false || isAutoGeneratedRouteTitle(draftTitle, initialSport)));

        if (editDraft?.route_points?.points?.length) {
          loadedDraftRef.current = true;
          const geometry = normalizeRoutePoints(editDraft.route_points.points);
          const savedControls = normalizeRoutePoints(editDraft.route_points.waypoints || editDraft.route_points.control_points);
          const source = String(editDraft.route_points.source || "").toLowerCase();
          const editableControlPoints = savedControls.length >= 2
            ? compactControlPoints(savedControls)
            : source.includes("gpx") || geometry.length > 300
              ? [geometry[0], geometry[geometry.length - 1]].filter(Boolean)
              : compactControlPoints(geometry);

          setPointsPayload(makeRoutePointPayload(editableControlPoints, source.includes("gpx") ? "gpx-edit-control-points" : "draw-edit-control-points"));
          setRoutedPayload({
            ...editDraft.route_points,
            points: geometry,
            waypoints: editableControlPoints,
            control_points: editableControlPoints,
            point_count: geometry.length,
          });
          setRouteSegments([]);
          setRoutingStatus("done");
          setRoutingError("");
          setMessage("");
          window.sessionStorage.removeItem("endurance_route_edit_draft");
        }

        const { data } = await supabase.auth.getUser();
        const user = data?.user;

        if (!user?.id) {
          router.replace("/login");
          return;
        }

        const { data: profileRow, error } = await supabase
          .from("profiles")
          .select("id,name,email,avatar_url,role,onboarding_completed,blocked")
          .eq("id", user.id)
          .maybeSingle();

        if (error) throw error;

        if (!profileRow?.onboarding_completed) {
          router.replace("/onboarding");
          return;
        }

        if (profileRow?.blocked) {
          setMessage("Your account is blocked. Contact an administrator.");
          return;
        }

        setProfile(profileRow);
      } catch (error) {
        console.error("Draw route bootstrap error", error);
        setMessage(error?.message || "Could not open draw editor.");
      } finally {
        setChecking(false);
      }
    }

    bootstrap();
  }, [router]);


  useEffect(() => {
    if (checking || !sportId) return;
    if (currentLocationRequestedRef.current) return;

    currentLocationRequestedRef.current = true;

    const shouldFocusCurrentLocation = !loadedDraftRef.current && points.length === 0 && routedPoints.length === 0;
    requestCurrentLocation({ focus: shouldFocusCurrentLocation, quiet: true });
  }, [checking, sportId, points.length, routedPoints.length]);

  function requestCurrentLocation({ focus = true, quiet = false, allowRouteFocus = false } = {}) {
    if (!navigator.geolocation) {
      if (!quiet) setMessage("Geolocation is not available on this device.");
      return;
    }

    if (!quiet) setMessage("");

    navigator.geolocation.getCurrentPosition(
      (position) => {
        const location = {
          lat: Number(position.coords.latitude.toFixed(6)),
          lon: Number(position.coords.longitude.toFixed(6)),
          accuracy: Math.round(position.coords.accuracy || 35),
          label: "Current location",
        };

        setCurrentLocation(location);

        const hasRoute = points.length >= 2 || routedPoints.length >= 2;
        const mayFocus = focus && (!loadedDraftRef.current || allowRouteFocus) && (!hasRoute || allowRouteFocus);

        if (mayFocus) {
          setTargetLocation({
            ...location,
            selectedAt: Date.now(),
            zoom: 15,
          });
        }

        if (!quiet) {
          setMessage("");
        }
      },
      () => {
        if (!quiet) setMessage("Could not access current location. You can still search or draw manually.");
      },
      { enableHighAccuracy: true, timeout: 9000, maximumAge: 60000 }
    );
  }

  function fallbackSegmentPayload(segment, reason = "Routing provider could not snap this segment.") {
    const fallbackPoints = normalizeRoutePoints(segment?.control || [segment?.from, segment?.to]);
    return {
      ...segment,
      geometry: fallbackPoints,
      points: fallbackPoints,
      routed: false,
      status: "failed",
      fallback_reason: reason,
      quality: null,
      updated_at: new Date().toISOString(),
    };
  }

  async function routeSingleSegment(segment, syncId) {
    const cached = segmentCacheRef.current.get(segment.key);
    if (cached?.geometry?.length >= 2) return cached;

    try {
      const response = await fetch("/api/routes/reroute", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sport_id: sportId,
          points: segment.control,
        }),
      });

      const data = await response.json().catch(() => ({}));
      if (syncId !== segmentSyncIdRef.current) return null;

      if (!response.ok || !Array.isArray(data?.points) || data.points.length < 2) {
        throw new Error(data?.error || data?.warning || "No snapped segment returned.");
      }

      const routed = {
        ...segment,
        geometry: normalizeRoutePoints(data.points),
        points: normalizeRoutePoints(data.points),
        routed: data?.routed !== false,
        status: "ready",
        quality: data?.route_quality || null,
        updated_at: new Date().toISOString(),
      };

      segmentCacheRef.current.set(segment.key, routed);
      return routed;
    } catch (error) {
      console.warn("Segment routing fallback", error);
      const fallback = fallbackSegmentPayload(segment, error?.message || "Segment routing failed.");
      segmentCacheRef.current.set(segment.key, fallback);
      return fallback;
    }
  }

  async function syncRouteSegments(controlPoints, { silent = false } = {}) {
    const control = normalizeRoutePoints(controlPoints);

    if (control.length < 2) {
      setRouteSegments([]);
      setRoutedPayload(null);
      setRoutingStatus("idle");
      return;
    }

    const segments = getControlSegments(control);
    const syncId = segmentSyncIdRef.current + 1;
    segmentSyncIdRef.current = syncId;
    setRoutingStatus("loading");
    setRoutingError("");
    if (!silent) setMessage("Snapping route segments...");

    const previousGeometry = normalizeRoutePoints(routedPayload?.points);

    const previousMap = new Map(routeSegments.map((segment) => [segment.key, segment]));
    const initialSegments = segments.map((segment) => previousMap.get(segment.key) || { ...segment, geometry: segment.control, points: segment.control, status: "loading" });
    setRouteSegments(initialSegments);

    const routedSegments = await Promise.all(segments.map((segment) => routeSingleSegment(segment, syncId)));
    if (syncId !== segmentSyncIdRef.current) return;

    const validSegments = routedSegments.filter(Boolean);
    setRouteSegments(validSegments);
    const payload = buildRoutePayloadFromSegments(validSegments, "segment-snap");
    const nextGeometry = normalizeRoutePoints(payload.points);
    if (previousGeometry.length >= 2) {
      const nextMetrics = calculateRouteMetrics(nextGeometry);
      const previousMetrics = calculateRouteMetrics(previousGeometry);
      const grewTooMuch = previousMetrics.distance_km > 0 && nextMetrics.distance_km > previousMetrics.distance_km * 1.35;

      if (grewTooMuch && !silent) {
        setMessage("Keeping previous route because the snap result looked unstable.");
      }

      if (grewTooMuch) {
        setRoutedPayload({
          ...routePayloadFromGeometry(previousGeometry, control, "segment-snap-kept-previous"),
          unstable_snap_rejected: true,
          rejected_distance_km: nextMetrics.distance_km,
          previous_distance_km: previousMetrics.distance_km,
        });
        setRoutingStatus("done");
        setRoutingError("");
        return;
      }
    }

    if (payload?.points?.length >= 2) {
      setRoutedPayload({
        ...payload,
        source: "segment-snap",
        waypoints: control,
        control_points: control,
        route_quality: payload.route_quality || null,
        routed_at: new Date().toISOString(),
      });
      setRoutingStatus("done");
      setRoutingError("");
      if (!silent) setMessage("");
    } else {
      const fallback = routePayloadFromGeometry(control, control, "drawn-fallback");
      setRoutedPayload({ ...fallback, routed: false });
      setRoutingStatus("done");
      setRoutingError("");
      if (!silent) setMessage("Using the drawn line as a fallback.");
    }
  }

  useEffect(() => {
    if (checking || !sportId) return;
    if (loadedDraftRef.current && points.length < 3) return;
    if (suppressNextSegmentSyncRef.current) {
      suppressNextSegmentSyncRef.current = false;
      return;
    }

    if (points.length < 2) {
      setRouteSegments([]);
      setRoutedPayload(null);
      return;
    }

    const timeout = window.setTimeout(() => {
      syncRouteSegments(points, { silent: true });
    }, 450);

    return () => window.clearTimeout(timeout);
  }, [routeSignature, checking, sportId]);

  async function handleSearch() {
    const query = searchText.trim();
    if (!query) return;

    setSearching(true);
    setMessage("");

    try {
      const response = await fetch(`/api/geocode/search?q=${encodeURIComponent(query)}`);
      const data = await response.json().catch(() => ({}));

      if (!response.ok) throw new Error(data?.error || "Could not search this place.");

      setSearchResults(Array.isArray(data.results) ? data.results : []);
      if (!data.results?.length) setMessage("No places found. Try another search term.");
    } catch (error) {
      setMessage(error?.message || "Search failed.");
    } finally {
      setSearching(false);
    }
  }

  function handleSelectSearchResult(result) {
    const target = toMapPoint({ lat: result.lat, lon: result.lon, label: result.label, zoom: 15, selectedAt: Date.now() });
    if (!target) return;
    setTargetLocation(target);
    setSearchOpen(false);
    setSearchText(result.label || "");
    setSearchResults([]);
  }

  function handleTargetLocationHandled() {
    setTargetLocation(null);
  }

  function clearRoute() {
    if (!window.confirm("Clear this route?")) return;
    setPointsPayload(null);
    setRoutedPayload(null);
    setRouteSegments([]);
    setRoutingStatus("idle");
    setRoutingError("");
    setTitleEditedManually(false);
    setRouteStartLocation("Locatie bepalen");
    setMessage("");
    loadedDraftRef.current = false;
  }

  function undoPoint() {
    const next = points.slice(0, -1);
    setPointsPayload(makeRoutePointPayload(next));
    if (next.length < 2) {
      setRoutedPayload(null);
      setRouteSegments([]);
    }
  }

  async function addLoopPoint() {
    if (!points.length) {
      requestCurrentLocation({ focus: true, quiet: false });
      return;
    }

    const lastPoint = points[points.length - 1];
    const offset = 0.01;
    const nextPoint = {
      lat: Number((lastPoint.lat + offset).toFixed(6)),
      lon: Number((lastPoint.lon + offset).toFixed(6)),
    };
    const next = [...points, nextPoint, points[0]];
    setPointsPayload(makeRoutePointPayload(next));
  }

  function handlePointsChange(nextPoints) {
    const normalized = normalizeRoutePoints(nextPoints);
    setPointsPayload(makeRoutePointPayload(normalized));
  }

  async function handleLocalSegmentEdit(segmentEdit) {
    const insertAt = Number(segmentEdit?.insertAt);
    const editPoint = segmentEdit?.editPoint;

    if (!Number.isInteger(insertAt) || !editPoint) return;

    const next = [...points.slice(0, insertAt), editPoint, ...points.slice(insertAt)];
    const previous = points;
    suppressNextSegmentSyncRef.current = true;
    setPointsPayload(makeRoutePointPayload(next));
    setRoutingStatus("loading");
    setRoutingError("");
    setMessage("Updating this route segment...");

    try {
      const segmentControl = [previous[insertAt - 1], editPoint, previous[insertAt]].filter(Boolean);
      const response = await fetch("/api/routes/reroute", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sport_id: sportId,
          points: segmentControl,
        }),
      });

      const data = await response.json().catch(() => ({}));
      if (!response.ok || !Array.isArray(data?.points) || data.points.length < 2) {
        throw new Error(data?.error || data?.warning || "No snapped segment returned.");
      }

      const routed = normalizeRoutePoints(data.points);
      const mergedGeometry = mergeLocalSegmentGeometry(
        routedPayload?.points,
        previous,
        next,
        insertAt,
        routed
      );

      setRoutedPayload({
        ...routePayloadFromGeometry(mergedGeometry, next, data?.routed === false ? "manual-local-segment" : "local-segment-reroute"),
        profile: routed?.profile || null,
        provider_url: routed?.provider_url || null,
        route_quality: routed?.route_quality || data?.route_quality || null,
        routed_at: new Date().toISOString(),
      });
      setRoutingStatus("done");
      setRoutingError("");
      if (data?.routed === false) {
        setMessage(data?.warning || "No snapped path found. Using the drawn line.");
      }
    } catch (error) {
      console.error("Local segment rerouting failed", error);
      setRoutingStatus("error");
      setRoutingError(error?.message || "Local rerouting failed.");
      setMessage(error?.message || "Could not snap this segment to roads/paths.");
    }
  }


  async function handleNativeGeometrySegmentEdit(segmentEdit) {
    const geometry = normalizeRoutePoints(routedPayload?.points?.length ? routedPayload.points : activeRoutePayload);
    const geometryIndex = Number(segmentEdit?.geometryIndex);
    const beforeIndex = Number(segmentEdit?.beforeIndex);
    const afterIndex = Number(segmentEdit?.afterIndex);
    const editPoint = segmentEdit?.editPoint;

    if (geometry.length < 2 || !editPoint) {
      setMessage("Could not edit this segment.");
      return;
    }

    // GPX/native geometry edit mode:
    // Do not call ORS and do not rebuild the route. A GPX route is already a
    // complete geometry. Dragging an edit point should directly modify the
    // geometry array and redraw immediately.
    const targetIndex = Number.isInteger(geometryIndex)
      ? Math.max(1, Math.min(geometryIndex, geometry.length - 2))
      : Number.isInteger(beforeIndex) && Number.isInteger(afterIndex)
        ? Math.max(1, Math.min(Math.round((beforeIndex + afterIndex) / 2), geometry.length - 2))
        : -1;

    if (targetIndex < 1 || targetIndex >= geometry.length - 1) {
      setMessage("Could not edit this part of the route.");
      return;
    }

    const nextGeometry = geometry.map((point, index) =>
      index === targetIndex
        ? {
            ...point,
            lat: Number(editPoint.lat),
            lon: Number(editPoint.lon),
            ele: Number.isFinite(Number(editPoint.ele)) ? Number(editPoint.ele) : point.ele ?? null,
          }
        : point
    );

    const controls = normalizeRoutePoints(routedPayload?.waypoints || routedPayload?.control_points);
    const metrics = calculateRouteMetrics(nextGeometry);

    suppressNextSegmentSyncRef.current = true;
    setPointsPayload(makeRoutePointPayload(controls.length >= 2 ? controls : compactControlPoints(nextGeometry), "native-gpx-edit-control-points"));
    setRoutedPayload({
      ...(routedPayload && typeof routedPayload === "object" && !Array.isArray(routedPayload) ? routedPayload : {}),
      source: "native-gpx-direct-geometry-edit",
      points: nextGeometry,
      geometry_points: nextGeometry,
      waypoints: controls,
      control_points: controls,
      point_count: nextGeometry.length,
      distance_km: metrics.distance_km || null,
      elevation_gain_m: metrics.elevation_gain_m || 0,
      edited_at: new Date().toISOString(),
      edit_mode: "direct_geometry",
    });
    setRouteSegments([]);
    setRoutingStatus("done");
    setRoutingError("");
    setNativeEditStatus("edited");
    setMessage("");
    loadedDraftRef.current = true;
  }

  function handleNativeGeometryChange(nextGeometry, meta = {}) {
    const geometry = normalizeRoutePoints(nextGeometry);

    if (geometry.length < 2) return;

    const controls = normalizeRoutePoints(routedPayload?.waypoints || routedPayload?.control_points);
    const metrics = calculateRouteMetrics(geometry);

    suppressNextSegmentSyncRef.current = true;
    setPointsPayload(makeRoutePointPayload(controls.length >= 2 ? controls : compactControlPoints(geometry), "native-gpx-edit-control-points"));
    setRoutedPayload({
      ...(routedPayload && typeof routedPayload === "object" && !Array.isArray(routedPayload) ? routedPayload : {}),
      source: meta?.source || "native-gpx-geometry-edit",
      points: geometry,
      geometry_points: geometry,
      waypoints: controls,
      control_points: controls,
      point_count: geometry.length,
      distance_km: metrics.distance_km || null,
      elevation_gain_m: metrics.elevation_gain_m || 0,
      edited_at: new Date().toISOString(),
    });
    setRouteSegments([]);
    setRoutingStatus("done");
    setRoutingError("");
    setNativeEditStatus("edited");
    setMessage("");
    loadedDraftRef.current = true;
  }

  function buildCurrentDraft(titleOverride) {
    const isNativeGeometryDraft = loadedDraftRef.current && routedPayload?.points?.length >= 2;
    const safePayload = isNativeGeometryDraft
      ? buildFullGeometryRoutePayload(routedPayload, routedPayload.points)
      : buildSafeDraftRoutePayload(
          routedPayload?.points?.length ? routedPayload : makeRoutePointPayload(points),
          points
        );

    if (isNativeGeometryDraft) {
      const nativeControls = normalizeRoutePoints(routedPayload?.waypoints || routedPayload?.control_points);
      safePayload.waypoints = nativeControls;
      safePayload.control_points = nativeControls;
    } else {
      safePayload.waypoints = compactControlPoints(points);
      safePayload.control_points = compactControlPoints(points);
    }
    safePayload.geometry_points = safePayload.points;
    const readableStartLocation = cleanHumanLocationLabel(routeStartLocation);
    if (readableStartLocation && !/^locatie bepalen$/i.test(readableStartLocation)) {
      safePayload.start_location_label = readableStartLocation;
      safePayload.start_location = readableStartLocation;
    }

    const metricsForDraft = calculateRouteMetrics(safePayload);
    const nextTitle = titleOverride || title;

    return makeRouteDraft({
      sportId,
      title: nextTitle,
      profileId: profile?.id,
      metrics: metricsForDraft,
      routePayload: safePayload,
      titleIsAuto: !titleEditedManually && isAutoGeneratedRouteTitle(nextTitle, sportId),
    });
  }

  function saveDraftAndContinue() {
    const draft = buildCurrentDraft();
    window.sessionStorage.setItem("endurance_new_route_draft", JSON.stringify(draft));
    router.push("/routes/new/details");
  }

  async function getStableTitleForSave() {
    if (titleEditedManually && title.trim()) return title.trim();

    const geometry = normalizeRoutePoints(routedPayload?.points?.length ? routedPayload.points : activeRoutePayload);
    const first = geometry[0];
    const distance = calculateRouteMetrics(geometry).distance_km || metrics.distance_km || routedPayload?.distance_km || activeRoutePayload?.distance_km;
    let startLabel = cleanHumanLocationLabel(routeStartLocation);

    if ((!startLabel || /^locatie bepalen$/i.test(startLabel)) && first) {
      startLabel = await resolveHumanLocationLabelFromCoordinates(first);
    }

    const autoTitle = buildAutomaticRouteTitle({
      startLocation: startLabel,
      distanceKm: distance,
      sportId,
    });

    return autoTitle || title.trim() || defaultTitle(sportId);
  }

  async function continueToDetails() {
    if (!canContinue || !profile?.id) return;

    if (editRouteId) {
      try {
        setMessage("Saving route...");
        const activeGeometry = normalizeRoutePoints(routedPayload?.points?.length ? routedPayload.points : activeRoutePayload);
        const isNativeGeometrySave = loadedDraftRef.current && activeGeometry.length >= 2;

        const stableTitle = await getStableTitleForSave();
        const draft = buildCurrentDraft(stableTitle);
        const safeRoutePoints = isNativeGeometrySave
          ? {
              ...(routedPayload && typeof routedPayload === "object" && !Array.isArray(routedPayload) ? routedPayload : {}),
              points: activeGeometry,
              geometry_points: activeGeometry,
              point_count: activeGeometry.length,
              waypoints: normalizeRoutePoints(routedPayload?.waypoints || routedPayload?.control_points),
              control_points: normalizeRoutePoints(routedPayload?.control_points || routedPayload?.waypoints),
              source: routedPayload?.source || "native-gpx-direct-geometry-edit",
            }
          : draft.route_points;
        const normalizedRoutePoints = isNativeGeometrySave
          ? activeGeometry
          : normalizeRoutePoints(safeRoutePoints?.points);
        const normalizedWaypoints = isNativeGeometrySave
          ? normalizeRoutePoints(safeRoutePoints?.waypoints || safeRoutePoints?.control_points)
          : normalizeRoutePoints(safeRoutePoints?.waypoints || safeRoutePoints?.control_points);
        const metrics = calculateRouteMetrics(normalizedRoutePoints);

        if (normalizedRoutePoints.length < 2) throw new Error("Route geometry is missing.");

        const firstPoint = normalizedRoutePoints[0];
        const lastPoint = normalizedRoutePoints[normalizedRoutePoints.length - 1];
        const [startLabel, finishLabel] = await Promise.all([
          resolveHumanLocationLabelFromCoordinates(firstPoint),
          resolveHumanLocationLabelFromCoordinates(lastPoint),
        ]);

        const finalTitle = titleEditedManually
          ? stableTitle
          : buildAutomaticRouteTitle({
              startLocation: startLabel || routeStartLocation,
              distanceKm: metrics.distance_km,
              sportId,
            }) || stableTitle;
        const nextTitleIsAuto = !titleEditedManually && isAutoGeneratedRouteTitle(finalTitle, sportId);

        const routeUpdate = {
          title: finalTitle,
          title_is_auto: nextTitleIsAuto,
          description: draft.description || "",
          sport_id: sportId,
          distance_km: metrics.distance_km || null,
          elevation_gain_m: metrics.elevation_gain_m || 0,
          route_points: {
            ...safeRoutePoints,
            points: normalizedRoutePoints,
            geometry_points: normalizedRoutePoints,
            waypoints: normalizedWaypoints,
            control_points: normalizedWaypoints,
            point_count: normalizedRoutePoints.length,
            distance_km: metrics.distance_km || null,
            elevation_gain_m: metrics.elevation_gain_m || 0,
            source: isNativeGeometrySave
              ? (safeRoutePoints?.source || "native-gpx-direct-geometry-edit")
              : (safeRoutePoints?.source || "draw-fullscreen-edit"),
            start_location: startLabel || safeRoutePoints?.start_location || null,
            start_location_label: startLabel || safeRoutePoints?.start_location_label || null,
            finish_location: finishLabel || safeRoutePoints?.finish_location || null,
            finish_location_label: finishLabel || safeRoutePoints?.finish_location_label || null,
          },
          start_location: startLabel || null,
          finish_location: finishLabel || null,
          route_version: Date.now(),
          source_type: inferRouteSourceType({
            route_points: {
              ...safeRoutePoints,
              points: normalizedRoutePoints,
            },
            gpx_file_url: draft.gpx_file_url,
          }),
          updated_at: new Date().toISOString(),
        };

        const { data: updatedRoute, error: routeError } = await supabase
          .from("routes")
          .update(routeUpdate)
          .eq("id", editRouteId)
          .eq("creator_id", profile.id)
          .select("id")
          .maybeSingle();

        if (routeError) throw routeError;
        if (!updatedRoute?.id) throw new Error("Route could not be saved.");

        const geometryInsert = buildRouteGeometryInsert({
          route_id: updatedRoute.id,
          route_points: routeUpdate.route_points,
          version: routeUpdate.route_version,
          source_type: routeUpdate.source_type,
          distance_km: routeUpdate.distance_km,
          elevation_gain_m: routeUpdate.elevation_gain_m,
        });

        const { data: geometryRow, error: geometryError } = await supabase
          .from("route_geometries")
          .insert(geometryInsert)
          .select("id,version")
          .single();

        if (geometryError) throw geometryError;

        const { error: linkError } = await supabase
          .from("routes")
          .update({ geometry_id: geometryRow.id, route_version: geometryRow.version, updated_at: new Date().toISOString() })
          .eq("id", updatedRoute.id)
          .eq("creator_id", profile.id);

        if (linkError) throw linkError;

        window.sessionStorage.removeItem("endurance_route_edit_draft");
        setMessage("Route saved.");
        router.replace(editReturnTo || `/routes/${updatedRoute.id}`);
        return;
      } catch (error) {
        console.error("Route update failed", error);
        setMessage(error?.message || "Could not save route.");
        return;
      }
    }

    saveDraftAndContinue();
  }

  function handleTitleChange(event) {
    setTitle(event.target.value);
    setTitleEditedManually(true);
  }

  function downloadGpx() {
    const geometry = normalizeRoutePoints(routedPayload?.points?.length ? routedPayload.points : activeRoutePayload);

    if (geometry.length < 2) {
      setMessage("No route geometry available for GPX export.");
      return;
    }

    const safeName = (title || "endurance-route").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "endurance-route";
    downloadTextFile({
      filename: `${safeName}.gpx`,
      text: routePointsToGpx(geometry, title),
    });
  }

  if (checking) {
    return (
      <main className="route-draw-fullscreen route-draw-loading">
        <div>
          <strong>Opening route studio...</strong>
          <span>Preparing map tools</span>
        </div>
      </main>
    );
  }

  const center = getCenterPoint(routedPoints.length ? routedPoints : points);
  const elevationValue = Math.round(metrics.elevation_gain_m || 0);
  const drawMapLayer = drawLayer;

  return (
    <main className="route-draw-fullscreen">
      <RouteDrawMap
        points={points}
        routedPoints={routedPoints}
        onChange={handlePointsChange}
        onNativeGeometrySegmentEdit={handleNativeGeometrySegmentEdit}
        onNativeGeometryChange={handleNativeGeometryChange}
        nativeGeometryEdit={loadedDraftRef.current && routedPoints.length >= 2}
        height="100%"
        layer={drawMapLayer}
        onLayerChange={setDrawLayer}
        routeMode={routeSegments.length ? "segmented" : routedPoints.length >= 2 ? "routed" : "drawn"}
        currentLocation={currentLocation}
        focusCurrentLocation={currentLocation ? { ...currentLocation, selectedAt: Date.now(), zoom: 15 } : null}
        targetLocation={targetLocation}
        onTargetLocationHandled={handleTargetLocationHandled}
      />

      <div className="route-draw-topbar">
        <button type="button" className="route-draw-back" onClick={() => router.back()} aria-label="Back">←</button>
        <input value={title} onChange={handleTitleChange} aria-label="Route title" />
        <button type="button" className="route-draw-save" onClick={continueToDetails} disabled={!canContinue || routingStatus === "loading"}>
          {editRouteId ? "Save route" : "Continue"}
        </button>
      </div>

      <div className="route-draw-controls route-draw-controls-left">
        <ControlButton icon="⌖" label="Current Location" onClick={() => requestCurrentLocation({ focus: true, quiet: false, allowRouteFocus: true })} />
        <ControlButton icon="⌕" label="Search" onClick={() => setSearchOpen((value) => !value)} />
        <ControlButton icon="◌" label="Loop" onClick={addLoopPoint} disabled={loadedDraftRef.current && points.length < 3} />
        <ControlButton icon="↶" label="Undo" onClick={undoPoint} disabled={!points.length} />
        <ControlButton icon="⌫" label="Clear" onClick={clearRoute} danger />
        <ControlButton icon="◎" label="Quality" onClick={() => setShowQualityPanel((value) => !value)} disabled={!routeQuality} />
        <ControlButton icon="△" label="Elevation" onClick={() => setShowElevationPanel((value) => !value)} />
        <ControlButton icon="GPX" label="Export" onClick={downloadGpx} disabled={normalizeRoutePoints(activeRoutePayload).length < 2} />
        <ControlButton icon="▦" label="Layers" onClick={() => setShowPointPanel((value) => !value)} />
      </div>

      {searchOpen && (
        <section className="route-draw-search-panel">
          <form onSubmit={(event) => { event.preventDefault(); handleSearch(); }}>
            <input value={searchText} onChange={(event) => setSearchText(event.target.value)} placeholder="Search place or address" />
            <button type="submit" disabled={searching}>{searching ? "..." : "Search"}</button>
          </form>
          {searchResults.length > 0 && (
            <div className="route-draw-search-results">
              {searchResults.slice(0, 6).map((result) => (
                <button key={`${result.lat}-${result.lon}-${result.label}`} type="button" onClick={() => handleSelectSearchResult(result)}>
                  <strong>{result.label}</strong>
                  <span>{Number(result.lat).toFixed(4)}, {Number(result.lon).toFixed(4)}</span>
                </button>
              ))}
            </div>
          )}
        </section>
      )}

      {showQualityPanel && <RouteQualityPanel payload={routedPayload || activeRoutePayload} sportId={sportId} onClose={() => setShowQualityPanel(false)} />}
      {showPointPanel && <MapStylePanel value={drawLayer} onChange={setDrawLayer} onClose={() => setShowPointPanel(false)} />}
      {showElevationPanel && (
        <section className="route-draw-elevation-panel">
          <button type="button" onClick={() => setShowElevationPanel(false)}>×</button>
          <strong>Elevation gain</strong>
          <b>{elevationValue} m+</b>
          <span>{metrics.distance_km ? `${metrics.distance_km.toFixed(2)} km route` : "Draw or edit a route"}</span>
        </section>
      )}

      <div className="route-draw-bottom-metric">
        <span>Elevation</span>
        <strong>{elevationValue} m+</strong>
      </div>

      {message && <div className="route-draw-message">{message}</div>}
      {routingStatus === "loading" && <div className="route-draw-status">Snapping route...</div>}
      {routingError && <div className="route-draw-error">{routingError}</div>}
    </main>
  );
}
